// Snake traps: scenes that try to tempt you into office-snake behaviour. Each bait looks clever in the moment
// (a quick win, being in the know, looking indispensable) and costs trust later. Each lesson is drawn from
// research on workplace politics: negative gossip, credit claiming, knowledge hiding, blame contagion,
// ingratiation, social undermining, triangulation and rumour. All names are fictional.

export const TRAPS = [
  // ---------------- DAY 2: gossip ----------------
  {
    id: 'trap_gossip', day: 2, title: 'The pantry whisper', mode: 'choose', diff: 1, npc: 'bao', place: 'pantry', time: 'Tue 15:10',
    hb: 'Snake trap', hook: 'warnings', min: 2,
    trap: { sin: 'Gossip', vi: 'Buôn chuyện', lure: 'Gossip feels like bonding, and knowing first feels like status.' },
    setting: 'The pantry, Floor 6. The kettle is taking forever. {bao} leans on the counter with a grin.',
    cue: '"Have you noticed {dat.s}? Long lunches, ironed shirt, phone face down. He\'s interviewing, one hundred percent. Who do you reckon, a fintech?"',
    prompt: 'What do you do?',
    opts: [
      { t: '"Ha, and he changed his profile photo last week. Definitely a fintech." Add your clue to the case.', g: 'D', bait: true, fx: { bao: 1, vis: 1, dat: -3, trust: -2, pol: -1 }, expr: 'smile',
        r: '{bao.s} laughs, delighted. By 16:30 "{dat.s} is leaving" has reached two floors, with "{me} spotted the profile photo" attached. {dat.s} was at his son\'s school all week. Somewhere, a faint hiss.',
        why: 'Listeners tend to pin the traits you describe onto you. Spread a story about someone being disloyal and people quietly file you under "not safe to confide in".' },
      { t: 'Lean in: "I won\'t say a word. But tell me everything."', g: 'C', bait: true, fx: { bao: 1, trust: -1, pol: -1 }, expr: 'lean',
        r: '{bao.s} tells you everything, which is nothing, at length. Later he tells someone else that you "seemed very interested".',
        why: 'An eager audience is half of every rumour. Listening hungrily makes you a co-author, even if you never repeat a word.' },
      { t: '"No idea, and I\'d rather ask him than guess. Anyway, how did your prototype review go?"', g: 'A', fx: { bao: 1, trust: 1 }, expr: 'warm',
        r: '"Fair. Ugh, the review." He\'s off on a new topic, and a better one.',
        why: 'Decline lightly and change the subject to the person in front of you. No lecture, no fuel.' },
      { t: 'Redirect warmly now, and later send {dat.s} a quiet "coffee tomorrow? I\'ve barely seen you this week", without mentioning any rumour.', g: 'S', fx: { bao: 1, dat: 2, trust: 2, pol: 1 }, expr: 'warm',
        r: 'Over coffee {dat.s} mentions, almost in passing, that things at home have been heavy. He thanks you for asking about him, not about his calendar.',
        why: 'Gossip treats a colleague as a story. Checking in treats him as a person. The second is what people remember when they choose whom to trust.' },
    ],
    timeout: { g: 'C', fx: { vis: -1 }, r: 'You mumble something about the kettle. {bao.s} takes your silence as a yes.', why: 'Silence in a gossip moment reads as agreement. One light, kind sentence is enough.' },
  },

  // ---------------- DAY 4: credit ----------------
  {
    id: 'trap_credit', day: 4, title: '"Whose idea was this?"', mode: 'choose', diff: 2, npc: 'anh_khai', place: 'desk', time: 'Thu 11:05',
    hb: 'Snake trap', hook: 'currencies', min: 2,
    trap: { sin: 'Credit stealing', vi: 'Cướp công', lure: 'He is impressed right now, and nobody would know the difference.' },
    setting: 'Your desk. {khai} stops by to see the Lantern prototype. {vy} sits two seats away, pretending not to listen.',
    cue: 'He taps the exception filter that {vy.s} designed last week. "This is clever. Whose idea was it?"',
    prompt: 'What do you do?',
    opts: [
      { t: '"It came out of my method. I set the pattern and the team filled it in." Technically, you did write the playbook.', g: 'D', bait: true, fx: { anh_khai: 1, vis: 1, vy: -3, trust: -2 }, expr: 'smile',
        r: '{khai.s} nods, impressed. Next week he asks {vy.s} a detail about "your" filter, and she answers it better than you ever could. He looks at you for a long second. Hiss.',
        why: 'Taking credit from a junior is seen by everyone except the person you are trying to impress, and sometimes by them too. Leaders who give credit precisely are seen as more competent, not less.' },
      { t: '"Honestly, a team effort."', g: 'C', fx: { vy: -1 }, expr: 'neutral',
        r: '"Great team." He moves on. {vy.s} looks at her screen.',
        why: 'Vague credit erases the person who earned it. "Team" is generous only when you can also name names.' },
      { t: '"That\'s {vy}\'s. {vy.s}, want to show anh how it handles the edge cases?"', g: 'A', fx: { vy: 2, anh_khai: 1, trust: 1 }, expr: 'warm',
        r: '{vy.s} walks him through it, nervous at first, then clear. He asks her two questions.',
        why: 'Handing the floor to the person who did the work is the fastest way to show you multiply people.' },
      { t: '"{vy.s} designed it. Her call was to put exceptions first; I pushed her on the edge cases. She\'s right there if you want the detail."', g: 'S', fx: { anh_khai: 2, vy: 3, trust: 2, vis: 1 }, expr: 'warm',
        r: '"Good. That\'s what I like to hear." He nods to {vy.s}, who goes pink and grins.',
        why: 'Specific credit to her, plus the honest part you played as coach. He hears a designer and a future manager in one sentence.' },
    ],
    timeout: { g: 'C', fx: { vis: -1, vy: -1 }, r: 'You hesitate, and he answers for you: "Your work, I assume." Nobody corrects him.', why: 'Silence can steal credit too. Name the person, quickly.' },
  },

  // ---------------- DAY 6: going over your manager's head ----------------
  {
    id: 'trap_overhead', day: 6, title: 'The lift question', mode: 'choose', diff: 2, npc: 'anh_khai', place: 'lift', time: 'Mon 08:55',
    hb: 'Snake trap', hook: 'no3b', min: 2,
    trap: { sin: 'Going over your manager\'s head', vi: 'Vượt mặt sếp', lure: 'Thirty seconds alone with the person who could just fix it.' },
    setting: 'The lift, Floor 1 to Floor 6. Just you and {khai}.',
    cue: 'Lantern\'s release slipped two weeks after {ethan.s} approved a late scope add you argued against. {khai.s} smiles: "How\'s Lantern going?"',
    prompt: 'What do you do?',
    opts: [
      { t: '"Honestly, two weeks late. {ethan.s} took on scope I warned him about. If you could nudge him, anh, it would really help."', g: 'D', bait: true, fx: { vis: 1, anh_khai: -1, ethan: -3, pol: -2 }, expr: 'neutral',
        r: '"I\'ll have a word with {ethan.s}." He does, by lunchtime, and helpfully mentions where he heard it. {ethan.s} walks over looking very calm. Too calm. Hiss.',
        why: 'Never Bypass, never Bitch. An executive who hears you criticise your manager assumes you would do the same about him.' },
      { t: '"Small slip. Between us, priorities on our side are a bit messy at the moment."', g: 'C', bait: true, fx: { vis: 1, ethan: -2, trust: -1 }, expr: 'lean',
        r: '"Messy how?" Now you are explaining your manager\'s decisions to his boss\'s peer, between floors 4 and 5.',
        why: 'A hint is still a complaint, with deniability. It invites the very question you should not answer.' },
      { t: '"All good, thanks anh!"', g: 'C', fx: { trust: -1 }, expr: 'smile',
        r: '"Great." When he hears about the slip next week, he remembers the lift.',
        why: 'Hiding bad news is the other trap. Executives forgive misses, not surprises.' },
      { t: '"Core release on track; one feature two weeks later because we chose to add it. {ethan.s} and I have a plan, and I\'m sure he\'d be happy to walk you through it." Then tell {ethan.s} about the lift.', g: 'S', fx: { anh_khai: 1, ethan: 2, trust: 2 }, expr: 'warm',
        r: '"Good, no surprises. Thanks." Back at your desk, {ethan.s} says: "Cheers for the heads-up. I\'ll send him a note."',
        why: 'Headline honest, decision owned as "we", and the line keeps the story. That protects {ethan.s} and makes you look like someone who can carry news upward safely.' },
    ],
    timeout: { g: 'C', fx: { vis: -1 }, r: 'The doors open on Floor 6 before you find the words.', why: 'Prepare a one-line status for the lift. It saves you from both oversharing and hiding.' },
  },

  // ---------------- DAY 8: knowledge hoarding ----------------
  {
    id: 'trap_hoard', day: 8, title: 'The secret prompt library', mode: 'choose', diff: 2, npc: 'antoine', place: 'teams', time: 'Tue 10:20',
    hb: 'Snake trap', hook: 'reciprocity', min: 2,
    trap: { sin: 'Knowledge hoarding', vi: 'Giấu nghề', lure: 'If only you can do it, they can never do without you.' },
    setting: 'Teams. A message from {antoine}, Head of Skills Guild.',
    cue: '"Your prompt library is legendary. Could we publish it to all designers in the Guild next week? Happy to put your name on it."',
    prompt: 'What do you do?',
    opts: [
      { t: '"It\'s still quite rough, let me tidy it up first." Then never quite get round to it. Indispensable people don\'t get reorganised.', g: 'D', bait: true, fx: { deliv: 1, antoine: -2, bao: -1, pol: -2 }, expr: 'neutral',
        r: 'Three weeks later {bao.s} publishes his own library. It is half as good and has his name on it. {antoine.s}\'s newsletter calls him "the AI multiplier". Hiss.',
        why: 'Knowledge hiding tends to come back as distrust: colleagues stop sharing with the hider, and the hider\'s own ideas dry up.' },
      { t: 'Share a cleaned-up version, minus the twelve prompts that really work.', g: 'C', bait: true, fx: { antoine: 1, trust: -2, craft: -1 }, expr: 'neutral',
        r: 'A designer messages: "Mine never come out like yours. Is something missing?" Several people now wonder the same thing.',
        why: 'Half-sharing is still hiding, and it is easy to spot. People compare results.' },
      { t: 'Send the files as they are, with a short readme.', g: 'B', fx: { antoine: 1, vis: 1 }, expr: 'smile',
        r: '"Brilliant, thanks!" A few people use it. Most get stuck on the context you never wrote down.',
        why: 'Generous, but a library without the method behind it rarely travels far.' },
      { t: '"Yes. I\'ll add a one-page guide on when each prompt is safe to use, run a 30-minute walkthrough, and ask {bao.s} to co-maintain it with me."', g: 'S', fx: { antoine: 3, bao: 2, vis: 2, energy: -1 }, expr: 'warm',
        r: 'Ninety designers attend. {bao.s} adds four prompts of his own. {antoine.s}: "Can I use your session as the learner story for the next Guild report?"',
        why: 'Your value is the judgment, not the file. Giving it away with your name on the method is what makes you the obvious person to lead it.' },
    ],
    timeout: { g: 'C', fx: { vis: -1 }, r: 'You leave it on read. {antoine.s} asks someone else.', why: 'A fast, generous yes is a visibility gift. Silence gives it away.' },
  },

  // ---------------- DAY 9: blame ----------------
  {
    id: 'trap_blame', day: 9, title: 'The demo bug', mode: 'choose', diff: 2, npc: 'sarah', place: 'meeting', time: 'Wed 16:40',
    hb: 'Snake trap', hook: 'own_control', min: 2,
    trap: { sin: 'Blame-shifting', vi: 'Đổ lỗi', lure: 'One sentence and the bug becomes someone else\'s problem.' },
    setting: 'Demo to {sarah} from Melbourne. {chau} is on the call, camera off.',
    cue: 'The loan summary shows a settlement date in 1970. {sarah.s}: "Well. That\'s a vintage loan. What happened there?"',
    prompt: 'What do you do?',
    opts: [
      { t: '"That\'s a backend issue on the engineering side, not the design."', g: 'D', bait: true, fx: { cred: 1, sarah: -1, minh_chau: -3, trust: -2 }, expr: 'cool',
        r: '{chau.s} unmutes: "It\'s the test data file uploaded this morning. By {me}." A very long pause from Melbourne. Hiss.',
        why: 'Blame is contagious: once one person shifts it, the whole room starts protecting itself. And owning a miss often turns out to be the first step to trust.' },
      { t: '"Ah, the AI does that sometimes."', g: 'C', bait: true, fx: { sarah: -1, cred: -1 }, expr: 'smile',
        r: '{sarah.s} laughs. The next morning {raj} asks which step of your AI method is uncontrolled.',
        why: 'Blaming the tool is still blaming. It also tells the Risk Guardian your method has a hole.' },
      { t: 'Laugh, skip that screen and keep going.', g: 'C', fx: { sarah: -1 }, expr: 'smile',
        r: 'She lets it go. She does not forget it.',
        why: 'Skipping hides the problem without owning it. She wants bad news handled, not dodged.' },
      { t: '"That\'s wrong, and it\'s mine to chase. The rest of the screen is real data. I\'ll send you the corrected view by tomorrow, your morning."', g: 'S', fx: { sarah: 2, minh_chau: 1, trust: 2 }, expr: 'warm',
        r: '"Love that. Plain answer." After the call {chau.s} messages: "Test file, I think. I\'ll check with you."',
        why: 'Own it, fix it, fix the control. People who admit a mistake make it easier for everyone else to do the same.' },
    ],
    timeout: { g: 'C', fx: { sarah: -1 }, r: 'A silence long enough for {sarah.s} to check her watch.', why: 'Have a one-line ownership answer ready: what is wrong, who is fixing it, by when.' },
  },

  // ---------------- DAY 10: silent sabotage ----------------
  {
    id: 'trap_sabotage', day: 10, title: 'Slide 6', mode: 'choose', diff: 3, npc: 'bao', place: 'desk', time: 'Thu 18:40',
    hb: 'Snake trap', hook: 'rivals', min: 2,
    trap: { sin: 'Silent sabotage', vi: 'Chơi xấu', lure: 'You did not cause his mistake. You would just look better next to it.' },
    setting: 'Your desk, late. {bao.s} shared his deck for tomorrow\'s review with {khai} and asked the team for "any typos".',
    cue: 'Slide 6 counts the saved hours twice. His headline number is double what it should be. {khai.s} always checks the maths.',
    prompt: 'What do you do?',
    opts: [
      { t: 'Say nothing. You were asked about typos, not maths.', g: 'D', bait: true, fx: { vis: 1, bao: -3, pol: -2, trust: -1 }, expr: 'neutral',
        r: '{khai.s} finds it in ninety seconds. {bao.s} flounders. Afterwards he checks the file history: "You opened this at 18:40 last night." Hiss.',
        why: 'Withholding help to let a colleague fail is social undermining, one of the most damaging behaviours at work. When it is discovered, trust rarely comes back.' },
      { t: 'Wait for the review, then helpfully point it out in front of {khai.s}.', g: 'D', bait: true, fx: { vis: 1, bao: -3, anh_khai: -1 }, expr: 'cool',
        r: '{khai.s}: "Good catch." Then, a beat later: "When did you spot it?"',
        why: 'Catching a peer out in front of a senior wins a point and loses a peer. Seniors notice timing.' },
      { t: 'Mention it to {bao.s} in passing tomorrow morning.', g: 'B', fx: { bao: 1 }, expr: 'neutral',
        r: 'He fixes it in a panic ten minutes before the review. "Thanks. Could have said last night."',
        why: 'Right act, poor timing. A warning is worth more the earlier it arrives.' },
      { t: 'Message him tonight: "Slide 6 might count the hours twice, quick fix. Want a second pair of eyes on the rest?"', g: 'S', fx: { bao: 3, pol: 2, trust: 1 }, expr: 'warm',
        r: '"Oh no. Oh no. Thank you." The review goes well. Next week he brings you into his project.',
        why: 'Today\'s peer is tomorrow\'s sponsor or blocker. A private save is the cheapest alliance you will ever buy.' },
    ],
    timeout: { g: 'D', fx: { bao: -2 }, r: 'You close the laptop meaning to mention it. You don\'t.', why: 'Not deciding is deciding. Send the message tonight.' },
  },

  // ---------------- DAY 11: ingratiation ----------------
  {
    id: 'trap_suckup', day: 11, title: 'The chatbot for everything', mode: 'choose', diff: 2, npc: 'anh_khai', place: 'meeting', time: 'Fri 14:10',
    hb: 'Snake trap', hook: 'no_public', min: 2,
    trap: { sin: 'Flattery', vi: 'Nịnh sếp', lure: 'He is the one who decides your future. Agreeing loudly costs nothing.' },
    setting: 'A meeting room. {khai}, {chau} and {lan} around the table.',
    cue: '{khai.s}: "What if we put an AI chatbot on every lending form by Q1? All of them." {chau.s} raises one eyebrow. Everyone looks at you.',
    prompt: 'What do you do?',
    opts: [
      { t: '"Anh, that\'s honestly the best idea I\'ve heard this year. I can start Monday."', g: 'D', bait: true, fx: { anh_khai: 1, vis: 1, minh_chau: -2, chi_lan: -2, cred: -2 }, expr: 'smile',
        r: '{khai.s} looks pleased. {lan.s}, in the corridor afterwards: "So you\'re building forty chatbots by Monday?" Hiss.',
        why: 'Observers dislike people who are sweet upward, and flattery can push leaders into overconfident calls that later hurt everyone, including the flatterer.' },
      { t: 'Nod along, say "sounds great", and add nothing.', g: 'C', fx: { cred: -1 }, expr: 'neutral',
        r: 'The meeting moves on. Your nod is recorded as a yes.',
        why: 'Silent agreement is quieter flattery. It leaves him without the data he needs.' },
      { t: '"Which form hurts bankers most today? That might be the one to start with."', g: 'A', fx: { anh_khai: 1, cred: 1 }, expr: 'lean',
        r: '"Good question. Probably the guarantee form." The plan gets smaller and better.',
        why: 'A question that sharpens his idea is support with substance. He keeps ownership.' },
      { t: '"I like the direction. One data point that might help: on Lantern, AI help worked on simple fields and confused people on complex ones. Could we pilot one form, measure, then scale?"', g: 'S', fx: { anh_khai: 2, minh_chau: 2, cred: 2 }, expr: 'warm',
        r: '{chau.s}: "Measured how?" {khai.s}: "Good. One form first. {me}, draft the measure." The eyebrow comes down.',
        why: 'Real support is helping his idea succeed. Offer one data point, give him room, and the room sees someone who can be trusted with the truth.' },
    ],
    timeout: { g: 'C', fx: { vis: -1 }, r: 'Someone else answers. The moment passes.', why: 'Have one useful question ready. It beats both flattery and silence.' },
  },

  // ---------------- DAY 12: the punitive CC ----------------
  {
    id: 'trap_cc', day: 12, title: 'The CC of doom', mode: 'choose', diff: 2, npc: 'minh_chau', place: 'teams', time: 'Mon 09:15',
    hb: 'Snake trap', hook: 'prewire', min: 2,
    trap: { sin: 'Public shaming by CC', vi: 'CC sếp để bêu', lure: 'One CC and the thing you need arrives in forty minutes.' },
    setting: 'Your inbox. The API spec from {chau}\'s team is three days late and blocking Lantern testing.',
    cue: 'Your cursor hovers over the CC field. {khai}\'s name autocompletes helpfully.',
    prompt: 'What do you do?',
    opts: [
      { t: 'Reply-all with {khai.s} in CC: "Just following up for visibility, this is now blocking Lantern."', g: 'D', bait: true, fx: { deliv: 1, vis: 1, minh_chau: -3, anh_khai: -1, pol: -2 }, expr: 'cool',
        r: 'The spec arrives in forty minutes. So does a reply from {chau.s}, also copying {khai.s}, attaching your test plan from last month, which was two weeks late. Hiss.',
        why: 'Copying the boss to apply pressure reads as distrust, and research finds people copied in this way feel watched and less trusted. They remember who did it.' },
      { t: 'Wait another week. You don\'t want to be a nag.', g: 'C', fx: { deliv: -2 }, expr: 'neutral',
        r: 'Testing slips. Now you have your own delay to explain.',
        why: 'Avoiding conflict is not the same as being kind. Delay costs everyone.' },
      { t: 'A private message: what it is blocking, by when you need it, and an offer of a 15-minute call.', g: 'A', fx: { minh_chau: 1, deliv: 1 }, expr: 'neutral',
        r: '"Fair. Thursday?" Clear and civil.',
        why: 'Impact and a date, privately. Most delays clear with one direct, specific message.' },
      { t: 'Walk over: "What\'s blocking the spec? Anything I can take off your plate?" Agree a date together, and agree that if it slips again you\'ll both raise it.', g: 'S', fx: { minh_chau: 2, deliv: 1, pol: 1 }, expr: 'warm',
        r: '{chau.s}: "Two people out sick. If you write the field list, we\'ll do the rest by Wednesday." It arrives Tuesday.',
        why: 'Start with what is in their way. Escalate together, not against them, and only if you must.' },
    ],
    timeout: { g: 'C', fx: { deliv: -1 }, r: 'The draft sits in your outbox all morning.', why: 'Decide: direct, private and specific beats both silence and the CC.' },
  },

  // ---------------- DAY 13: the meeting after the meeting ----------------
  {
    id: 'trap_afterparty', day: 13, title: 'The meeting after the meeting', mode: 'choose', diff: 2, npc: 'bao', place: 'teams', time: 'Tue 16:05',
    hb: 'Snake trap', hook: 'candor', min: 2,
    trap: { sin: 'Two-faced agreement', vi: 'Trước mặt một đằng, sau lưng một nẻo', lure: 'Nodding in the room is easy, and the side chat feels like real friendship.' },
    setting: 'Teams, five minutes after {lan} closed the design review. Everyone agreed to her navigation direction.',
    cue: '{bao.s} in a side chat: "That direction is so dated. Let\'s just build ours in the prototype. She won\'t notice for weeks."',
    prompt: 'What do you do?',
    opts: [
      { t: '"Agreed. Ship ours, ask forgiveness later."', g: 'D', bait: true, fx: { bao: 2, chi_lan: -3, trust: -2, pol: -1 }, expr: 'smile',
        r: '{lan.s} opens the prototype the next morning, not in weeks. "Who decided this?" {bao.s}, quickly: "It was {me}\'s idea." Hiss.',
        why: 'Agreeing in the room and undermining afterwards is the fastest way to lose a Craft Guardian. Side chats rarely stay on the side.' },
      { t: 'Drop a thumbs-up and say nothing.', g: 'C', bait: true, fx: { bao: 1, trust: -1 }, expr: 'neutral',
        r: 'Your thumbs-up is now part of the plan, as far as {bao.s} is concerned.',
        why: 'A reaction is a vote. Silence in a side chat counts as agreement.' },
      { t: '"I had doubts too, but we agreed in the room. Let\'s build hers well and log our concern for the next review."', g: 'A', fx: { chi_lan: 1, bao: -1, trust: 1 }, expr: 'neutral',
        r: '{bao.s}: "Fine, boring." But he logs it.',
        why: 'Disagree, then commit. The concern goes on record, not underground.' },
      { t: '"If we think it\'s wrong, let\'s tell her. I\'ll ask {lan.s} for 15 minutes tomorrow with both of us, and we bring one quick test."', g: 'S', fx: { chi_lan: 2, bao: 1, trust: 2 }, expr: 'warm',
        r: '{lan.s} looks at the test and changes one thing. "Thank you for bringing it to me first." {bao.s} gets to present it.',
        why: 'Care personally, challenge directly. Bringing the disagreement into the room keeps the trust and often improves the work.' },
    ],
    timeout: { g: 'C', fx: { trust: -1 }, r: 'You leave it unread. {bao.s} takes that as a yes.', why: 'A side chat needs a clear answer, kindly.' },
  },

  // ---------------- DAY 15: the screenshot ----------------
  {
    id: 'trap_screenshot', day: 15, title: 'The screenshot', mode: 'choose', diff: 3, npc: 'ethan', place: 'teams', time: 'Thu 21:30',
    hb: 'Snake trap', hook: 'discretion', min: 2,
    trap: { sin: 'Snitching for favour', vi: 'Chụp màn hình mách sếp', lure: 'Show the boss you are the loyal one, with proof.' },
    setting: 'A designers\' group chat. {bao} and three others are venting about {ethan}\'s new 45-minute stand-up.',
    cue: 'One message reads: "Stand-up is where joy goes to die." It is funny. It is also very screenshot-shaped.',
    prompt: 'What do you do?',
    opts: [
      { t: 'Screenshot it and send to {ethan.s}: "Thought you should know what people are saying."', g: 'D', bait: true, fx: { ethan: 1, vis: 1, bao: -3, trust: -3, pol: -2 }, expr: 'neutral',
        r: '{ethan.s} thanks you. At the next stand-up he says: "I hear some of you find this pointless." Five heads turn to work out who was in the chat. A new group appears the next day, without you. Hiss.',
        why: 'Informers buy one moment of favour and lose the group for good. Your manager also learns you forward private chats, and wonders what you forward about him.' },
      { t: 'Quietly leave the group.', g: 'C', fx: { pol: -1 }, expr: 'neutral',
        r: 'Nobody asks why. They just stop telling you things.',
        why: 'Exiting avoids the trap but loses your view of what the team really thinks.' },
      { t: 'Tell {ethan.s} the theme in your own words, no names: "A few of us find stand-up long. Could we try 15 minutes for a fortnight?"', g: 'A', fx: { ethan: 1, trust: 1 }, expr: 'warm',
        r: '"Really? Huh. Yeah, let\'s try it."',
        why: 'Carry the signal, not the source. Feedback without names is useful; feedback with screenshots is surveillance.' },
      { t: 'In the chat: "Fair points. Want me to take the stand-up length to {ethan.s} as a team suggestion, no names?" Then do it.', g: 'S', fx: { ethan: 1, bao: 1, trust: 2, pol: 1 }, expr: 'warm',
        r: 'Three thumbs up. Stand-up becomes 15 minutes. {bao.s}: "OK, you\'re useful."',
        why: 'You turned a vent into a proposal, with the group\'s consent. Loyalty is shown in private, and trust runs both ways.' },
    ],
    timeout: { g: 'C', fx: { vis: -1 }, r: 'You scroll past. The vent keeps growing.', why: 'Venting that nobody channels tends to curdle. Offer a route.' },
  },

  // ---------------- DAY 16: triangulation ----------------
  {
    id: 'trap_triangle', day: 16, title: 'The go-between', mode: 'choose', diff: 2, npc: 'vy', place: 'desk', time: 'Mon 11:30',
    hb: 'Snake trap', hook: 'safety_candor', min: 2,
    trap: { sin: 'Triangulation', vi: 'Đâm bị thóc, chọc bị gạo', lure: 'Everyone confides in you. That feels like being trusted.' },
    setting: 'Your desk. Yesterday {dat} complained that {vy} ignores the design system. Today {vy} arrives, upset.',
    cue: '{vy.s}: "{dat.s} keeps changing my components without asking. Can you say something to him?"',
    prompt: 'What do you do?',
    opts: [
      { t: '"Between us, {dat.s} said yesterday that you skip the system."', g: 'D', bait: true, fx: { vy: -1, dat: -2, trust: -2, pol: -1 }, expr: 'lean',
        r: '{vy.s} goes quiet, then asks {dat.s} directly whether he said that. He did. He also now knows who told her. Hiss.',
        why: 'Carrying one person\'s words to another feels like honesty and works like a match. Both of them stop confiding in you.' },
      { t: '"Leave it with me, I\'ll sort {dat.s} out."', g: 'C', bait: true, fx: { vy: 2, dat: -2, energy: -2, trust: -1 }, expr: 'warm',
        r: 'You relay her version. {dat.s} replies with his. By Thursday they both message you separately, at 22:00.',
        why: 'The go-between becomes the switchboard. Conflict carried by a third person lasts longer, because the two people never talk.' },
      { t: 'Listen, sympathise, and suggest she talk to him at some point.', g: 'B', fx: { vy: 1 }, expr: 'warm',
        r: '"Okay. Maybe." She doesn\'t.',
        why: 'Kind, but "some point" never arrives for someone who needs explicit safety to raise problems.' },
      { t: '"Have you told him how it lands? Let\'s grab him now. I\'ll sit in for the first five minutes, then leave you two to it."', g: 'S', fx: { vy: 2, dat: 2, trust: 2 }, expr: 'warm',
        r: 'Ten minutes later they are drawing on the same whiteboard. {dat.s}: "I didn\'t know she\'d built those. Sorry."',
        why: 'Get the two people talking, and make it safe enough to happen. That is what a manager does.' },
    ],
    timeout: { g: 'C', fx: { vy: -1 }, r: '"Never mind." She walks back to her desk.', why: 'A complaint is a request for help. Answer it with a route, not a shrug.' },
  },

  // ---------------- DAY 17: kiss up, kick down ----------------
  {
    id: 'trap_kickdown', day: 17, title: 'Ten minutes before {michael.s}', mode: 'choose', diff: 3, npc: 'vy', place: 'desk', time: 'Tue 09:50',
    hb: 'Snake trap', hook: 'gallup70', min: 2,
    trap: { sin: 'Kiss up, kick down', vi: 'Trên nịnh dưới chèn', lure: 'A sharp word shows the bar is high, and the visitor is not here yet.' },
    setting: 'Your desk. {michael}, visiting from Australia, arrives in ten minutes for the Lantern demo.',
    cue: '{vy.s}\'s demo file still shows last week\'s numbers. She sees your face. "Sorry, I\'ll fix..."',
    prompt: 'What do you do?',
    opts: [
      { t: '"Seriously? Again? This is why juniors don\'t do executive demos." Then turn and beam as {michael.s} walks in.', g: 'D', bait: true, fx: { deliv: 1, vy: -3, trust: -2, pol: -1 }, expr: 'cool',
        r: '{michael.s} arrived early. He was behind you. "Morning!" he says, warmly. Later he asks {ethan.s}: "Is {me} always like that with the team?" Hiss.',
        why: 'People who are sweet upward and sharp downward are disliked and distrusted by everyone who sees both sides, and executives look for exactly that.' },
      { t: 'Take the file and fix it yourself, saying nothing.', g: 'C', fx: { deliv: 1, vy: -1, energy: -1 }, expr: 'neutral',
        r: 'The numbers are right. {vy.s} watches her work disappear.',
        why: 'Fixing it silently tells her she is not trusted to fix it. Fine once, corrosive as a habit.' },
      { t: '"Okay, swap in the live data. I\'ll open with the story slide to buy you two minutes."', g: 'A', fx: { vy: 2, deliv: 1 }, expr: 'neutral',
        r: 'The numbers update during your story. Nobody notices.',
        why: 'Calm and a plan. Pressure travels down; so does steadiness.' },
      { t: '"Ten minutes is plenty. You do the numbers, I\'ll check the flow. We\'ll talk later about a pre-demo checklist." Then credit her by name in the demo.', g: 'S', fx: { vy: 3, deliv: 1, trust: 1, michael: 1 }, expr: 'warm',
        r: '{michael.s}: "Who built this filter?" "{vy.s}." She answers his question beautifully. Afterwards you build the checklist together.',
        why: 'Managers drive most of the difference in how engaged a team is. Steady under pressure, credit in public, fix the process later.' },
    ],
    timeout: { g: 'C', fx: { vy: -1 }, r: 'You sigh loudly. That says enough.', why: 'Under pressure, your face is the message. Lead with the plan.' },
  },

  // ---------------- DAY 19: the leak ----------------
  {
    id: 'trap_leak', day: 19, title: '"You\'d know, right?"', mode: 'choose', diff: 2, npc: 'bao', place: 'cafe', time: 'Wed 12:40',
    hb: 'Snake trap', hook: 'rumours', min: 2,
    trap: { sin: 'Leaking rumours', vi: 'Tung tin đồn', lure: 'Being the one who knows feels like being senior.' },
    setting: 'The café downstairs. Reorg rumours have been everywhere for a week. You glimpsed a draft org chart on {khai}\'s screen yesterday.',
    cue: '{bao.s}, stirring his coffee: "You\'re close to {khai.s}. What\'s really happening with Client Platforms?"',
    prompt: 'What do you do?',
    opts: [
      { t: '"I can\'t say much, but we\'re merging with Lending. Keep it quiet."', g: 'D', bait: true, fx: { vis: 1, bao: 1, anh_khai: -3, trust: -3, pol: -2 }, expr: 'lean',
        r: 'By Friday "the merger" is in three group chats. It was one option of four. {khai.s} asks, gently, where it might have started. Hiss.',
        why: 'Rumours spread fastest when people feel uncertain, and leakers lose the trust of both the source and the listener. If you leak this, what else would you leak?' },
      { t: 'A knowing smile: "Let\'s just say interesting times."', g: 'C', bait: true, fx: { vis: 1, bao: -1, trust: -1 }, expr: 'smile',
        r: '{bao.s} tells everyone you know something. You are now a source without having said a word.',
        why: 'Hinting is leaking with deniability. It feeds the rumour and paints you as a gatekeeper.' },
      { t: '"No idea, sorry."', g: 'B', fx: { trust: 1 }, expr: 'neutral',
        r: '"Hm. Okay." He doesn\'t quite believe you.',
        why: 'Discreet, but it leaves his worry untouched.' },
      { t: '"Honestly, I don\'t know what\'s decided, and if I did it wouldn\'t be mine to share. What\'s worrying you about it?"', g: 'S', fx: { bao: 2, trust: 2 }, expr: 'warm',
        r: '{bao.s} admits he is worried about his own role. You talk about the work he can control. He leaves calmer.',
        why: 'Be the calm one: don\'t speculate or spread, and listen to the worry underneath the question.' },
    ],
    timeout: { g: 'C', fx: { bao: -1 }, r: 'You stall too long. Your silence becomes "{me} knows something".', why: 'A rehearsed, honest line protects you and the source.' },
  },

  // ---------------- DAY 20: claim jumping ----------------
  {
    id: 'trap_claimjob', day: 20, title: 'The promised project', mode: 'choose', diff: 3, npc: 'anh_khai', place: 'restaurant', time: 'Thu 12:30',
    hb: 'Snake trap', hook: 'peer_leader', min: 2,
    trap: { sin: 'Claim jumping', vi: 'Hớt tay trên', lure: 'Your sponsor is asking. One word from him and it is yours.' },
    setting: 'Lunch with {khai}. {antoine} has already promised the Skills Guild AI cohort lead to {bao}. You would be good at it.',
    cue: '{khai.s}: "Anything you\'d like to take on next quarter? I can put in a word."',
    prompt: 'What do you do?',
    opts: [
      { t: '"The Guild cohort lead. Honestly, I\'d be stronger than {bao.s} on it. A word to {antoine.s} would do it."', g: 'D', bait: true, fx: { vis: 1, anh_khai: -1, bao: -3, antoine: -2, pol: -2 }, expr: 'lean',
        r: '{khai.s} mentions it to {antoine.s}, who says: "That\'s promised to {bao.s}. {me} knows that." {bao.s} hears by Monday. Hiss.',
        why: 'Sponsors spend reputation on you. Asking one to undo a peer\'s promise spends it on a fight, and he notices.' },
      { t: '"Nothing specific. But if {bao.s} can\'t manage the cohort, I\'m around."', g: 'C', bait: true, fx: { bao: -1, anh_khai: -1, pol: -1 }, expr: 'neutral',
        r: '{khai.s}: "Why wouldn\'t he manage?" You now have to explain a doubt you planted.',
        why: 'Planting doubt about a peer is lobbying in disguise. Senior people hear it instantly.' },
      { t: '"Nothing comes to mind, anh. I\'m focused on Lantern."', g: 'C', fx: { vis: -1 }, expr: 'neutral',
        r: '"Okay." He moves on. The offer does not come back this quarter.',
        why: 'Too modest. When a sponsor offers help, have one honest, specific ask ready.' },
      { t: '"{bao.s} is leading the Guild cohort, and I\'d love to back him by co-teaching the governed-AI module. Separately, I\'d value your view on a stretch that would build my people-leading evidence."', g: 'S', fx: { anh_khai: 2, bao: 2, antoine: 1, pol: 2 }, expr: 'warm',
        r: '{khai.s}: "Good answer. Let me think about the team leadership piece." {bao.s} accepts your offer that afternoon.',
        why: 'Help the peer win and ask for your own stretch openly. Sponsors back people who make others look good.' },
    ],
    timeout: { g: 'C', fx: { vis: -1 }, r: 'You hesitate; he picks up the menu.', why: 'Prepare your one ask before every sponsor lunch.' },
  },
];

// Why each trap matters for you, the risks it trains against, and two follow-up questions with sample answers.
export const TRAP_DEEP = {
  trap_gossip: {
    you: 'You are known as a quiet, steady supporter, and that reputation is an asset worth guarding. The fastest way to lose it is to be the person who adds one more detail to a pantry story. In a small design chapter, every rumour reaches its subject within a week, along with who added what.',
    risk: ['H9'],
    follow: [
      { by: 'bao', q: 'You really didn\'t want to know whether {dat.s} is leaving?',
        a: 'Honestly, I was curious too. But guessing about someone\'s job hunt can hurt them, and if it turned out wrong we would be the ones who started it. If {dat.s} is leaving, he will tell us when he is ready. I\'d rather check he is okay than check his calendar. Anyway, I want to hear how your review went, because last time you said the stakeholder kept moving the goalposts on you.' },
      { by: 'coach', q: 'Why does gossip hurt the gossiper, not just the target?',
        a: 'Because people tend to attach the traits you describe to you. If I talk about someone being disloyal, a little of that disloyalty sticks to me in the listener\'s mind. They also do the obvious maths: if I share this about him, I will share things about them. So I make my pantry rule simple. I talk about work and about people who are present, and I check on people directly.' },
    ],
  },
  trap_credit: {
    you: 'Your dossier says your best stories are outcomes and teaching, and panels look for proof that you multiply people. Precise credit to {vy.s} in front of {khai.s} is that proof, live. Claiming her work would trade your strongest manager signal for one compliment.',
    risk: ['H6', 'H9'],
    follow: [
      { by: 'anh_khai', q: 'So what was your part in the filter?',
        a: 'Honestly, the coaching, not the idea. {vy.s} came up with putting exceptions first. My part was pushing her on the edge cases, like partial settlements, and helping her test it with two operations users. That is the part of my work I most want to grow: helping designers like her get to a good answer faster. Next sprint she is leading the audit history screen, and I am pairing with her on it.' },
      { by: 'vy', q: 'Why did you name me? You could have just said "the team".',
        a: 'Because it was your idea and you deserved to hear it said out loud. "The team" sounds generous but it hides the person who did the work. I also wanted {khai.s} to know your name, because people like him remember names when opportunities come up. Next time something you made comes up with a senior person, I\'d love you to present it yourself. Want to practise a two-minute version on Friday?' },
    ],
  },
  trap_overhead: {
    you: 'This is risk H3 in its most tempting form: a private moment with an executive from another division and a real grievance about your manager. {khai.s} will judge how you would talk about him by how you talk about {ethan.s}. Your cross-division path depends on {ethan.s}\'s goodwill.',
    risk: ['H3'],
    follow: [
      { by: 'ethan', q: 'Did {khai.s} ask you about the slip?',
        a: 'Yes, in the lift this morning, so I wanted you to hear it from me straight away. I said the core release is on track and one feature is two weeks later because we chose to add it, and that you and I have a plan. I suggested you might brief him properly. Nothing negative was said. Would it help if I drafted the two-line note for you to send him today?' },
      { by: 'coach', q: 'You disagreed with {ethan.s}\'s call. Where does that disagreement belong?',
        a: 'With {ethan.s}, directly, and I already said it before he decided. Once he made the call, it became our decision in front of anyone else. If I think the pattern keeps hurting delivery, I will raise it with him again with numbers: what the late scope cost and what we could do differently. Complaining upward feels like a shortcut, but it only teaches senior people that I am unsafe to work with.' },
    ],
  },
  trap_hoard: {
    you: 'Your genuine edge is being very current on AI, and your dossier lists "you multiply others" as a core strength. Hoarding the library would protect the edge for a month and erase the multiplier story for good. Giving it away, with your name on the method, is what turns a skilled designer into the obvious lead.',
    risk: ['H6', 'H10'],
    follow: [
      { by: 'antoine', q: 'Aren\'t you worried that once everyone has it, you\'re less special?',
        a: 'A little, honestly. But the prompts are not the valuable part. The judgment about when each one is safe to use, and how to check the output, is what makes them work, and that grows when more people use it and tell me what breaks. If ninety designers get faster, that is a bigger story than one fast designer. Could we track before and after on three learners so we have a measured result?' },
      { by: 'bao', q: 'Why ask me to co-maintain it?',
        a: 'Because you are better than me at the visual prompts, and the library needs that. It also should not depend on one person. If I am on leave or busy, somebody needs to keep it current. I would like your name next to mine on it, and I\'d like you to present the visual section at the Guild session next month. Can we spend thirty minutes on Thursday sorting out which prompts need work first?' },
    ],
  },
  trap_blame: {
    you: 'Your credibility with {sarah.s} and {chau.s} rests on numbers that hold up. A demo bug is a small test of the same thing: do you own what is yours under pressure? Shifting it to engineering would also make an enemy of the Data-Driven Sceptic, the person whose respect you most need.',
    risk: ['H1'],
    follow: [
      { by: 'sarah', q: 'So what actually went wrong with that date?',
        a: 'A test data file I uploaded that morning had a blank date field, and the screen read blank as 1970. That one is on me. The design was fine, the data check was not. I have fixed the file and added a rule that test data gets validated before any demo. Your corrected screen is in your inbox, and I have flagged the two other screens that use the same field.' },
      { by: 'minh_chau', q: 'Why did you say it was yours before you knew?',
        a: 'Because the demo was mine, so the first answer had to be mine too. If I had pointed at your team and been wrong, you would have spent a day defending yourselves instead of helping me find it. It turned out to be my test file, so owning it early was also accurate. Next time anything breaks in one of my demos, I will check my own inputs first and call you second.' },
    ],
  },
  trap_sabotage: {
    you: '{bao.s} is your most important peer: talented, competitive and insecure about AI. Your dossier warns that becoming "his person" too visibly creates envy. Quietly saving his review tonight is the strongest move you have against that envy turning into a blocker.',
    risk: ['H9'],
    follow: [
      { by: 'bao', q: 'Why did you help me? You could have let me trip.',
        a: 'Because we are on the same side, and a wrong number in front of {khai.s} would have hurt all of us, not only you. Executives remember when a team\'s numbers wobble. I would want you to tell me if my deck had a mistake, and I hope you will. Honestly, the rest of your deck was strong. Want to swap decks before every big review from now on, two days ahead?' },
      { by: 'coach', q: 'What is the real cost of staying silent here?',
        a: 'The obvious cost is {bao.s}\'s trust when he works out I saw it, and file histories mean he probably would. The bigger cost is what {khai.s} learns about the team: that we let each other fail. Undermining a peer by withholding help is invisible until it is not, and then it defines you. A private two-line message costs me thirty seconds and buys an ally for years.' },
    ],
  },
  trap_suckup: {
    you: 'You are early in {khai.s}\'s orbit, and the temptation to agree loudly is strongest now. But he spotted you for a method that is fast and honest. Flattery would make you look like a fan, not a future leader, and {chau.s} and {lan.s} would quietly mark you down for it.',
    risk: ['H9', 'H5'],
    follow: [
      { by: 'anh_khai', q: 'Do you think the chatbot idea is a good one?',
        a: 'I think the direction is right, and I would test it before scaling it. On Lantern we saw AI help on simple fields but confuse people on complex ones, so I would expect mixed results across forty forms. If we pilot the guarantee form for four weeks and measure completion time and errors against today, we will know where it works. I can draft that measure plan by Wednesday.' },
      { by: 'chi_lan', q: 'You challenged him in front of us. Weren\'t you nervous?',
        a: 'Yes, a little. But I did not really challenge him; I offered one data point and a way to make his idea succeed. Agreeing with everything would have been easier and less useful. Leaders get flattery all day, and it can push them into big calls without the facts. I would rather be the person who helps him get it right. And I would value your view on how the forms should feel.' },
    ],
  },
  trap_cc: {
    you: 'Your profile shows you are steady with operations and engineering partners, and Lantern depends on them. A punitive CC would win one deadline and lose {chau.s} for the rest of the project. It would also show {khai.s} that you escalate before you talk to people.',
    risk: ['H3'],
    follow: [
      { by: 'minh_chau', q: 'Why didn\'t you just escalate? Everyone else does.',
        a: 'Because escalating first would have told you I did not trust you, and I needed your help more than your fear. I assumed there was a reason, and there was: two people out sick. Writing the field list was a small price for a spec two days later. If it had slipped again, I would have asked you to raise it with me, together, not around you. Thanks for turning it round so quickly.' },
      { by: 'coach', q: 'When is copying a senior person actually right?',
        a: 'When they need the information to make a decision, not when I want to apply pressure. If a delay changes a date that an executive has promised someone, I tell them directly, ideally with the other person, and with a plan. The test I use is simple: would I be comfortable if the other person knew why I added the name? If the honest answer is "to make them look bad", I take it out.' },
    ],
  },
  trap_afterparty: {
    you: '{lan.s} is the Craft Guardian who wants to be consulted before, not informed after. Agreeing in her review and building something else behind it is the precise opposite. You need her support for anything design-led you propose, and she will remember who went around her.',
    risk: ['H3', 'H6'],
    follow: [
      { by: 'chi_lan', q: 'Why bring me the concern instead of just building it your way?',
        a: 'Because it is your decision, and you can only make a good one if you hear the doubts. We should have said it in the review; we did not, so we came back as soon as we could. The quick test showed one real problem and two things your direction does better than ours. I am happy to build yours, with that one change. Would you like to see the test results in detail?' },
      { by: 'bao', q: 'You made us look like we were complaining. Why not just do it quietly?',
        a: 'Because quietly would have been worse when she found out, and she always finds out. Raising it openly made us look like people who care about the work, and you presented the test, so she saw your thinking first. Next time we disagree in a review, let\'s say so in the room, even briefly. I will back you up if you raise it, and I would like the same from you.' },
    ],
  },
  trap_screenshot: {
    you: 'Your reputation among peers is "quiet but consistent supporter". Forwarding a screenshot would turn that into "the one who reports us", and you would never get it back. Managers need people who carry honest signals upward without burning the people who shared them.',
    risk: ['H9'],
    follow: [
      { by: 'ethan', q: 'Is the team really unhappy with stand-up?',
        a: 'Not unhappy with you, but the forty-five minutes is wearing people down. A few of us talked about it and we would love to try fifteen minutes for two weeks, with deeper topics moved to a separate slot. I said I would bring it to you as a team suggestion, so I am not going to name anyone. If it helps, I can draft a simple format and we can review it together after two weeks.' },
      { by: 'coach', q: 'Wouldn\'t forwarding the chat have shown loyalty to your manager?',
        a: 'It would have shown loyalty for one evening. After that, he would wonder what I forward about him, and the team would stop talking near me. Real loyalty to {ethan.s} is helping him run a team that works, and that needs the honest signal, not the names. So I carry the theme, I propose a fix, and I keep the people safe. That is the kind of manager I want to become.' },
    ],
  },
  trap_triangle: {
    you: 'Your dossier names the gap that panels see: little evidence of handling conflict between people. {vy.s} and {dat.s} have handed you a perfect chance to show it. Carrying messages between them would feel helpful and teach them never to talk to each other.',
    risk: ['H6'],
    follow: [
      { by: 'vy', q: 'Why didn\'t you just tell {dat.s} to stop?',
        a: 'Because then it becomes my fight, and you two still would not know what the other one needed. When I carry your words, they change on the way, and he hears my version, not yours. You explained it really clearly just now. He did not know you had built those components. Next time something bothers you, try telling him first, and if it gets stuck, I am happy to sit in again.' },
      { by: 'coach', q: 'What does triangulation cost a team over time?',
        a: 'It keeps conflict alive, because the two people never solve it, they just keep reporting it. The go-between gets tired, then becomes the bottleneck, then gets blamed by both sides. It also teaches the team that the way to solve problems is to complain upward. The fix is small and repeatable: ask "have you told them?", offer to sit in once, then step back. That builds a team that can manage itself.' },
    ],
  },
  trap_kickdown: {
    you: 'You are trying to prove you can lead people, and executive visits are exactly when that is tested. How you treat {vy.s} with {michael.s} ten metres away is the evidence. Snapping down while smiling up is the one habit that makes senior people quietly decide you are not manager material.',
    risk: ['H6'],
    follow: [
      { by: 'vy', q: 'I\'m sorry about the numbers. Are you annoyed with me?',
        a: 'No, I am not. It was a small miss, and you fixed it in time, which is what matters. The real problem is that we had no checklist, and that is on me as much as you. Let\'s build a five-point pre-demo list together this afternoon. And you answered {michael.s}\'s question about the filter really well. I would like you to present that part yourself next time someone senior visits.' },
      { by: 'ethan', q: '{michael.s} said you were calm with the team. What was going on?',
        a: 'Ten minutes before he arrived, we found last week\'s numbers in the demo file. I asked {vy.s} to update them while I checked the flow, and opened with the story to buy time. It worked, and she handled his question about the filter better than I would have. We have since made a short pre-demo checklist, so it should not happen again. I will share it with the team on Monday.' },
    ],
  },
  trap_leak: {
    you: 'As {khai.s}\'s interest in you becomes visible, colleagues will assume you know things. Every time you resist that, you show you can be trusted with more. One leak would end his willingness to think out loud in front of you, and that is where sponsorship lives.',
    risk: ['H9'],
    follow: [
      { by: 'bao', q: 'Come on, you must know something about the reorg.',
        a: 'I really don\'t know what has been decided, and even if I had seen something, it would not be mine to share. I know that is frustrating. What I can do is tell you what I think matters regardless: delivery and good relationships tend to survive any reorg. If you are worried about your role, let\'s talk about that properly. What would make the next month feel more secure for you?' },
      { by: 'anh_khai', q: 'Have you been hearing a lot of rumours about the changes?',
        a: 'Yes, quite a lot this week, mostly about a merger. I have not added to them, and when people ask me I tell them I don\'t know, which is true. One thing that might help: people are mostly worried about their own roles, not the structure. If there is a way to share even a rough timeline, I think it would calm things. I am happy to help shape that message if useful.' },
    ],
  },
  trap_claimjob: {
    you: 'Your sponsor is offering to spend capital on you, and your dossier warns about asking too early and about envy. Taking a peer\'s promised role would hit both risks at once. Backing {bao.s} while asking openly for your own stretch shows {khai.s} exactly the leader he wants to invest in.',
    risk: ['H5', 'H9', 'H10'],
    follow: [
      { by: 'anh_khai', q: 'Why back {bao.s} instead of going for it yourself?',
        a: 'Because it was promised to him, and he will do it well. Taking it would have cost {antoine.s} a promise and me a peer. What I want next is evidence that I can lead people, and co-teaching his cohort gives me some of that. The bigger step would be leading a small team on a real delivery. Could I ask what you think would make me ready for that within six months?' },
      { by: 'bao', q: 'Did you try to get the cohort role?',
        a: 'No. {khai.s} asked what I would like to take on, and I said you are leading the cohort and I would love to back you on the governed-AI module. I also asked him about my own stretch, separately, because I want to grow too. I think you will do the cohort really well. If you want me on the module, can we sit down this week and plan the first session?' },
    ],
  },
};
