// WEEK 3: Acts II-IV "The Middle" → "The Board" (L5 Floor 12 → L10 Floor 27).
// Same schema as week1.js. checksRef on a scenario reuses another scenario's checks (retests).

export const LESSONS = {
  L15: {
    title: 'The middle',
    parts: [
      { type: 'predict', q: 'Restructure rumours sweep the floor. A colleague asks what you\'ve heard. What protects you most?',
        opts: [
          { t: 'Share what you know, people deserve to be prepared.', ok: false, why: 'Whatever you share becomes "{me} said…" by lunch.' },
          { t: 'Say you don\'t speculate, keep delivering, and listen if a leader raises it.', ok: true, why: 'In rumours, be the calm one. Leaders notice who stays steady.' },
          { t: 'Ask {khai.s} directly what\'s happening.', ok: false, why: 'Putting your sponsor in a position to leak or refuse costs him. If he raises it, listen.' },
        ] },
      { type: 'teach', h: 'Be the bridge, not the battlefield', body: [
        'When two senior people you depend on disagree, don\'t take sides in public. Bring the same facts to both. Suggest they talk directly. Your value to both is that you are not a weapon either can use.',
        'When someone warns you "be careful, he\'s political": thank them, don\'t pass it on, and watch for yourself. Trust patterns, not warnings.',
      ], hook: 'bridge' },
      { type: 'teach', h: 'Discretion is the price of trust', body: [
        'If your sponsor asks for information about your division you shouldn\'t share, decline politely and point to the right person. It may be a test; it is certainly a pattern he will remember either way.',
        'Loyalty is shown in private; facts are offered in public. If he is criticised by someone more senior in a meeting, stay quiet unless you have a fact that helps, then send a private note of support afterwards.',
      ], hook: 'discretion' },
      { type: 'teach', h: 'Pre-wire, keep quiet, no surprises', body: [
        'The Political Navigator\'s rule, and a good one for everyone: anyone who could be surprised in a meeting hears it from you first, one-to-one. "Before I raise this at steering committee, I wanted you to see it first."',
      ], hook: 'prewire' },
    ],
    cards: ['rumours', 'bridge', 'discretion', 'prewire', 'loyal_private', 'warnings'],
  },

  L16: {
    title: 'Care and clarity',
    parts: [
      { type: 'predict', q: 'A capable designer is missing deadlines. In the conversation, he becomes upset and mentions his mother is in hospital. What now?',
        opts: [
          { t: 'Drop the performance topic entirely, it would be cruel to continue.', ok: false, why: 'Care without clarity leaves him unsure where he stands and the team carrying the gap.' },
          { t: 'Acknowledge it first, then agree together what\'s realistic, and what support exists.', ok: true, why: 'Care first, clarity second, plan third, in that order, in one conversation.' },
          { t: 'Stay on the facts: deadlines are deadlines.', ok: false, why: 'Clarity without care breaks trust, and he will stop telling you anything.' },
        ] },
      { type: 'teach', h: 'Care first, clarity second, plan third', body: [
        'Care: stop, acknowledge, ask what he needs right now. Clarity: still say plainly what has been happening with the work and why it matters. Plan: agree together what changes, scope, dates, support (flexible hours, leave, the employee assistance programme via HR), and when you\'ll check in.',
        'Involve HR for options, not as a threat. Keep what he told you private; share only what others need to know to support the plan.',
      ], hook: 'ccp' },
      { type: 'teach', h: 'Safety and candour are partners', body: [
        'Psychological safety (Edmondson) is the belief that you won\'t be punished for speaking up. It isn\'t comfort; it is what makes candour possible. And candour is what makes safety worth having, a team that is safe but never challenged stops improving.',
      ], hook: 'safety_candor' },
      { type: 'pair', h: 'The moment it turns',
        weak: '"Oh no, I\'m so sorry. Don\'t worry about the work at all: take as long as you need. We\'ll figure it out."',
        strong: '"I\'m really sorry: thank you for telling me. Your mother comes first. Can I ask what would help most this week? … We still need to sort out the lending handoffs together so you\'re not carrying them in your head. Could we look at what to move off your plate, and I\'ll talk to {ha.s} about flexible hours?"',
        why: 'The weak version is kind and leaves him anxious about his job. The strong one is kind and clear: he knows you care and he knows the plan.' },
    ],
    cards: ['ccp', 'safety_candor'],
  },

  L17: {
    title: 'The culture lens',
    parts: [
      { type: 'predict', q: 'An Australian GM ends your status call with "Yeah, maybe: let\'s see." What does it most likely mean?',
        opts: [
          { t: 'Yes, probably.', ok: false, why: 'In Australian business English, "maybe" usually means no, said politely.' },
          { t: 'Probably no.', ok: true, why: 'Right. Check: "It sounds like you\'re not convinced: what\'s missing?"' },
          { t: 'She wasn\'t listening.', ok: false, why: 'She was. That\'s the problem.' },
        ] },
      { type: 'teach', h: 'Respect in form, crispness in content, candour in bad news', body: [
        'Vietnam: hierarchy and face matter; "yes" often means "I heard you"; bad news is softened. Singapore: direct, efficient, data-first; "yes" usually means yes. Australia: low hierarchy, first names, understatement; bad news expected early; "maybe" means no; over-selling is disliked.',
        'The rule for a Vietnam-based leader: Vietnamese respect in form, Singapore crispness in content, Australian candour in bad news.',
      ], hook: 'culture3' },
      { type: 'teach', h: 'Lead with control, not speed', body: [
        'To a Risk Guardian or an Australian sceptic, speed sounds like risk. Lead with traceability: "Speed is the side effect; what we optimised for was auditability, every decision links to its source." Then invite them to inspect.',
        'And if a data or privacy concern about your AI tooling is raised: in a bank, pause first, explain second. Stop the practice in question, engage Risk, document what data went where. Never minimise.',
      ], hook: 'control_speed' },
      { type: 'teach', h: 'Read the archetype from the first question', body: [
        '"How did you measure that?": Data Sceptic: label and methodology. "What controls are in place?": Risk Guardian: traceability. "What does this mean for my bankers?": Australian GM: banker outcome in plain English. "What do you need from me?": Overloaded Operator: one decision, or nothing. "What\'s the headline?": Group Executive: one story, one number.',
      ], hook: 'diag' },
    ],
    cards: ['culture3', 'au_yes', 'control_speed', 'pause_first', 'diag', 'visionary', 'operator', 'craft_g'],
  },

  L18: {
    title: 'Red at steering committee',
    parts: [
      { type: 'predict', q: 'Your program is red. Steering committee is tomorrow with {sarah.s}, {raj.s} and {khai.s}. When do they first hear it\'s red?',
        opts: [
          { t: 'Tomorrow, in the meeting, that\'s what steering committees are for.', ok: false, why: 'A red status in the room is a public surprise. Someone will feel ambushed.' },
          { t: 'Today, privately, one by one, with the recovery plan.', ok: true, why: 'No surprises in steering committees. In the room, you present the recovery plan, not the excuse.' },
          { t: 'After the meeting, if anyone asks.', ok: false, why: 'Hiding red is how offshore teams lose Australia\'s trust.' },
        ] },
      { type: 'teach', h: 'The room is for the recovery plan', body: [
        'BLUF-R privately beforehand, to each person who could be surprised. In the room: one line on status, one on cause, then the recovery plan and the one decision you need. Nobody wants the excuse; everybody wants the plan.',
      ], hook: 'red_steer' },
      { type: 'teach', h: '"What\'s the headline?"', body: [
        'When a Group Executive asks it, give one story, one number, and make your own executive look good. Never talk past your exec. "{khai.s} pushed us to prove it on a real lending epic: 6 weeks versus 14, measured."',
        'And your peers: today\'s peer is tomorrow\'s sponsor or blocker. Help them succeed in front of seniors.',
      ], hook: 'headline_q' },
    ],
    cards: ['red_steer', 'headline_q', 'peer_leader'],
  },

  L19: {
    title: 'Three sponsors',
    parts: [
      { type: 'predict', q: 'How many senior sponsors do you need?',
        opts: [
          { t: 'One great one.', ok: false, why: 'A single sponsor is a single point of failure. Sponsors move.' },
          { t: 'Three who would each independently say you should lead.', ok: true, why: 'The rule of three. Plus about eight advocates and thirty friends.' },
          { t: 'As many as possible.', ok: false, why: 'Sponsorship is spent reputation. You can\'t hold more than a few real ones.' },
        ] },
      { type: 'teach', h: '3 sponsors, 8 advocates, 30 friends', body: [
        'Tier 1, sponsors: every 4-6 weeks: a result, an advice ask, small help. Tier 2, advocates: monthly or per project. Tier 3, network: quarterly. And every Friday, fifteen minutes: review the log, send one result note and one thanks.',
      ], hook: 'three_sponsors' },
      { type: 'teach', h: 'How you lose is watched', body: [
        'If your sponsor gives your idea to someone else to lead: ask what was missing, then supply it, and offer to support. If you lose a role he backed you for: thank him, ask for the panel\'s feedback, congratulate the winner publicly. Sponsors watch how you lose more closely than how you win.',
      ], hook: 'lose_well' },
      { type: 'teach', h: 'Declared early, a footnote', body: [
        'Side work, a startup, a contract: declared early under policy, it\'s a footnote. Discovered late, it\'s a headline. If it surfaces and you haven\'t declared it, fix that immediately with your manager and HR.',
      ], hook: 'declare' },
    ],
    cards: ['three_sponsors', 'network', 'ask_missing', 'lose_well', 'declare'],
  },

  L20: {
    title: 'The line',
    parts: [
      { type: 'predict', q: 'Your sponsor asks you to present the pilot numbers to the board "without the caveats: they confuse people". What do you do?',
        opts: [
          { t: 'Do it. It\'s his call and the numbers are mostly right.', ok: false, why: '"Mostly right" without labels is misleading to a board. No sponsor is worth your integrity.' },
          { t: 'Decline privately, propose a clear version that keeps the labels, and escalate properly only if pressed.', ok: true, why: 'Protect him by protecting the truth, and give him an easy alternative.' },
          { t: 'Agree, then quietly add the caveats anyway.', ok: false, why: 'Agreeing and then doing otherwise is its own kind of dishonesty.' },
        ] },
      { type: 'teach', h: 'No sponsor is worth your integrity', body: [
        '"Anh, I don\'t think I can do that, the board would read it as measured across the portfolio, and it isn\'t. Could we show the measured epic big and the estimate labelled? It gets us most of the way." Privately, respectfully, with an alternative. If pressed further, the bank\'s speak-up process exists for exactly this.',
        'The manipulation test: "Would I be comfortable if he saw my notes?" Influence helps someone see what is true and useful. Manipulation doesn\'t.',
      ], hook: 'integrity' },
      { type: 'teach', h: 'When the sponsor leaves', body: [
        'Sponsors move: that is why you built three. Congratulate him genuinely, keep in touch, ask for one introduction to his successor, and strengthen the other relationships.',
        'And when you make a serious mistake: BLUF-R immediately, then over-deliver on the recovery. The recovery is remembered longer than the mistake.',
      ], hook: 'one_sponsor' },
    ],
    cards: ['integrity', 'one_sponsor', 'recovery', 'ethics5'],
  },

  L21: {
    title: 'The long game',
    parts: [
      { type: 'predict', q: 'Three weeks ago you started with one slide and one hint at coffee. What carried you furthest?',
        opts: [
          { t: 'The big moments, the lunch, the ask, the panel.', ok: false, why: 'They mattered, but each was won by small things before it.' },
          { t: 'Small promises kept fast, credit given away, and bad news told early.', ok: true, why: 'Reliability compounds. The bosses only checked whether it had.' },
          { t: 'Saying the right scripts.', ok: false, why: 'Scripts help you start. Consistency is what people trust.' },
        ] },
      { type: 'teach', h: 'Thirty, ninety, three-sixty-five', body: [
        'Thirty days to "interested", ninety to "trusted", a year to "leading". After month one, one meaningful touch every 4-6 weeks with a non-line executive: a result, an advice ask, small help.',
        'Part 0 in one breath: tell your manager, send CUP, ask advice, bring one gift, leave early.',
      ], hook: 'plan_arc' },
    ],
    cards: ['plan_arc', 'cadence', 'part0'],
  },
};

export const SCENARIOS = [
  // ---------------- DAY 15 ----------------
  {
    id: 'd15_rumour', day: 15, title: 'The rumour', mode: 'choose', diff: 2, npc: 'bao', place: 'pantry', time: 'Mon 08:50',
    hb: 'F8', hook: 'rumours', min: 3,
    setting: 'Floor 12. The pantry is louder than usual.',
    cue: '{bao.s}, now a manager on another team: "Heard Client Platforms is merging with Trading design. You\'re close to {khai.s}: what do you know?"',
    prompt: 'What do you say?',
    opts: [
      { t: '"Honestly, I don\'t speculate on those. If it\'s real, we\'ll hear properly. How\'s your team\'s launch going?"', g: 'S', fx: { pol: 3, bao: 1 }, tags: ['calm_in_rumours'], expr: 'neutral',
        r: '"…Fair. Launch is a mess, actually." You talk about that instead.', why: 'In rumours, be the calm one. You turned it to something useful.' },
      { t: '"Something might be happening: {khai.s} seemed stressed."', g: 'D', fx: { pol: -4, anh_khai: -3 }, tags: ['gossiped'], expr: 'neutral',
        r: 'By 11:00, "{me} said {khai.s} is stressed about the merger."', why: 'Even a hint becomes a quote. And it\'s about your sponsor.' },
      { t: '"No idea, but if it happens, I\'ll be fine."', g: 'C', fx: { bao: -1 }, expr: 'neutral',
        r: '{bao.s} raises an eyebrow.', why: 'Reads as smug. Calm is about the team, not just you.' },
      { t: 'Message {khai.s}: "Is the merger rumour true?"', g: 'C', fx: { anh_khai: -2 }, expr: 'neutral',
        r: '"Can\'t comment."', why: 'You put your sponsor in a position to leak or refuse. If he raises it, listen.' },
    ],
    ev: { id: 'calm_in_rumours', min: 'A' },
  },
  {
    id: 'd15_warn', day: 15, title: '"He\'s political"', mode: 'choose', diff: 2, npc: 'bao', place: 'pantry', time: 'Mon 09:00',
    hb: 'F9', hook: 'warnings', min: 2,
    setting: 'Still the pantry. {bao.s} lowers his voice.',
    cue: '"Be careful with {raj.s} in Risk, by the way. He\'s political: he killed my last project."',
    prompt: 'What do you do?',
    opts: [
      { t: '"Thanks for the heads-up." Don\'t repeat it, and form your own view in your next meeting with {raj.s}.', g: 'S', fx: { pol: 2 }, tags: ['patterns_not_warnings'], expr: 'neutral',
        r: 'Your first meeting with {raj.s} turns out precise and fair.', why: 'Collect perspectives; trust patterns, not warnings.' },
      { t: 'Avoid {raj.s} from now on.', g: 'C', fx: { raj: -2 }, expr: 'neutral',
        r: '{raj.s} notices you never consult him.', why: 'A Risk Guardian you avoid becomes a Risk Guardian who surprises you.' },
      { t: 'Warn your team about {raj.s}.', g: 'D', fx: { pol: -3, raj: -3 }, tags: ['gossiped'], expr: 'neutral',
        r: 'It reaches {raj.s} within a week.', why: 'Passing on a warning is passing on gossip.' },
    ],
  },
  {
    id: 'd15_bridge', day: 15, title: 'Two sponsors disagree', mode: 'choose', diff: 3, npc: 'chi_lan', place: 'meeting', time: 'Tue 14:00',
    hb: 'F6', hook: 'bridge', min: 3,
    setting: '{khai.s} wants the method rolled out to all twelve lending teams next quarter. {lan.s} thinks quality will collapse.',
    cue: '{lan.s}, privately: "You know this method best. Tell {khai.s} it can\'t scale that fast. He\'ll listen to you."',
    prompt: 'What do you do?',
    opts: [
      { t: 'Give both of them the same facts, what made the pilot work (a decision log, a weekly Ops partner) and what twelve teams would need, and suggest they talk directly, offering to join if useful.', g: 'S', fx: { chi_lan: 3, anh_khai: 3, pol: 3 }, tags: ['bridge'], expr: 'neutral',
        r: 'They meet. They agree on four teams first, then twelve.', why: 'Be the bridge, not the battlefield. Same facts to both; let them decide.' },
      { t: 'Tell {khai.s} that {lan.s} thinks his plan will fail.', g: 'D', fx: { chi_lan: -5, pol: -4 }, tags: ['backchannel'], expr: 'cool',
        r: '{lan.s} hears how it was framed.', why: 'Carrying one leader\'s criticism to another makes you a weapon.' },
      { t: 'Agree with whoever you\'re talking to at the time.', g: 'D', fx: { trust: -4 }, tags: ['two_faced'], expr: 'skeptic',
        r: 'Eventually they compare notes.', why: 'Inconsistency kills trust faster than disagreement.' },
      { t: 'Stay out of it entirely.', g: 'B', fx: {}, expr: 'neutral',
        r: 'They decide without the facts you had.', why: 'Neutral, but you held information both needed.' },
    ],
  },
  {
    id: 'd15_discretion', day: 15, title: '"Between us…"', mode: 'encounter', diff: 3, npc: 'anh_khai', place: 'lift', time: 'Wed 18:20', window: 6,
    hb: 'F5', hook: 'discretion', min: 2,
    setting: 'The lift. Just you and {khai.s}.',
    cue: '"Between us, how bad is morale in {ethan.s}\'s old team since the reorg? Who\'s thinking of leaving?"',
    prompt: 'Quick: answer.',
    opts: [
      { t: '"I\'m not the right person to share that, anh: {ethan.s} would know the real picture. Happy to connect you."', g: 'S', fx: { anh_khai: 3, trust: 3 }, tags: ['kept_discretion'], expr: 'neutral',
        r: 'He smiles slightly. "Good answer."', why: 'Discretion is the price of trust, and it may have been a test.' },
      { t: '"Honestly, two of them are interviewing elsewhere."', g: 'D', fx: { trust: -6, ethan: -4 }, tags: ['leaked'], expr: 'neutral',
        r: 'He nods. He now knows you would tell someone about him, too.', why: 'Whatever you share about others tells him what you would share about him.' },
      { t: '"Not great, but I don\'t want to name names."', g: 'C', fx: { trust: -1 }, expr: 'neutral',
        r: '"Hm."', why: 'Half-sharing still shares. Point him to the right person.' },
    ],
    timeout: { g: 'C', r: 'The doors open. You mumble something.', why: 'Have the line ready: "I\'m not the right person: {ethan.s} would know."' },
    ev: { id: 'kept_discretion', min: 'A' },
  },
  {
    id: 'd15_loyal', day: 15, title: 'Your sponsor, criticised', mode: 'choose', diff: 3, npc: 'michael', place: 'meeting', time: 'Thu 10:00',
    hb: 'D10', hook: 'loyal_private', min: 3,
    setting: 'A video call with Melbourne. {michael}, Group Executive, is unhappy.',
    cue: '{michael.s}: "Frankly, {khai.s}\'s area keeps promising AI wins and I\'m not seeing them in the numbers." {khai.s} is on the call. You have one fact that helps: the lending pilot\'s measured result.',
    prompt: 'What do you do?',
    opts: [
      { t: 'One factual line when there\'s a natural opening: "One data point that may help, lending discovery went from 14 weeks to 6, measured." Then, afterwards, a private note of support to {khai.s} with the one-page evidence.', g: 'S', fx: { anh_khai: 4, michael: 2 }, tags: ['loyal_private', 'made_exec_look_good'], expr: 'neutral',
        r: '{khai.s}, by message: "Thanks. That helped."', why: 'Loyalty is shown in private; facts are offered in public.' },
      { t: 'Defend him passionately: "That\'s not fair, he\'s done a lot."', g: 'C', fx: { michael: -3 }, expr: 'cool',
        r: '{michael.s}: "I\'m sure he has."', why: 'Emotion in public helps nobody. A fact would have.' },
      { t: 'Say nothing, then message a colleague about how harsh {michael.s} was.', g: 'D', fx: { pol: -4 }, tags: ['gossiped'], expr: 'neutral',
        r: 'Screenshots travel.', why: 'Gossip about a Group Executive is a career-length risk.' },
      { t: 'Stay silent throughout.', g: 'B', fx: {}, expr: 'neutral',
        r: 'The moment passes.', why: 'Safe, but you held the one fact that helped.' },
    ],
  },
  {
    id: 'd15_prewire', day: 15, title: 'Pre-wire {raj.s}', mode: 'type', diff: 2, npc: 'raj', place: 'teams', time: 'Fri 09:00', chat: true,
    hb: 'Part 15.7 · 15.3', hook: 'prewire', min: 5,
    setting: 'Teams, to {raj}, Head of Operational Risk.',
    cue: 'At Tuesday\'s steering committee you\'ll propose using a new AI summarisation tool on real lending applications. {raj.s} hasn\'t seen it.',
    prompt: 'Write the pre-wire note (about 55 words).',
    target: 55, maxQ: 1, dims: ['answer_first', 'brevity', 'other', 'next_step'],
    checks: [
      { dim: 'answer_first', l: 'Says why you\'re writing: before the meeting', lead: true, any: ['before (i raise|tuesday|steer)', 'ahead of', 'see it first', 'wanted you to'], ok: 'You named the pre-wire, no surprises.', fix: 'Open with: "Before I raise this at Tuesday\'s steering committee, I wanted you to see it first."' },
      { dim: 'other', l: 'Leads with controls (data, audit, human review)', any: ['control', 'data', 'audit', 'human review', 'traceab', 'privacy'], ok: 'Controls first, the Risk Guardian\'s language.', fix: 'Lead with controls: what data, what review, what audit trail.' },
      { dim: 'next_step', l: 'Invites his input or review', any: ['your (view|input|concerns)', 'review', '15 minutes', 'walk you through', 'what would you need'] },
      { dim: 'other', pen: 2, l: 'Leads with speed or hype', any: ['much faster', 'game.?chang', 'revolution', 'move fast', '10x'], fix: 'To a Risk Guardian, speed sounds like risk. Lead with control.' },
    ],
    model: 'Before I raise this at Tuesday\'s steering committee, I wanted you to see it first. We\'d like to trial an AI summariser on real lending applications, human review on every output, no data leaving our tenancy, full audit trail. What would you need to be comfortable? Happy to walk you through it in 15 minutes.',
    ev: { id: 'prewired', min: 'B' },
    react: {
      SA: { r: '"Thank you for coming to me first. Thursday 3pm, bring the data flow."', fx: { raj: 5, pol: 2 }, tags: ['prewired'], expr: 'warm' },
      B: { r: '"Noted. Send the details."', fx: { raj: 2 }, expr: 'neutral' },
      CD: { r: '"Let\'s discuss at steering committee."', fx: { raj: -1 }, expr: 'skeptic' },
    },
  },
  {
    id: 'd15_retest', day: 15, title: 'Retest: a first message, three weeks on', mode: 'type', diff: 2, npc: 'michael', place: 'teams', time: 'Fri 16:00', chat: true,
    hb: 'Part 4.2 · retest', hook: 'cup', min: 5, retestOf: 'd1_message',
    setting: 'Teams. A new chat with {michael}, Group Executive, after the call.',
    cue: 'After the tense call, {michael.s} said to the group: "I\'d like to see one of these AI wins up close next time I\'m in Ho Chi Minh City." You want to offer a short demo of the lending pilot.',
    prompt: 'Write the first message (CUP, ≤70 words).',
    target: 70, maxQ: 1, dims: ['answer_first', 'brevity', 'other', 'next_step', 'culture'],
    checks: [
      { dim: 'answer_first', l: 'Context in the opening line', lead: true, any: ['call', 'today', 'you mentioned', 'you said', 'earlier'], fix: 'Open with context: the call and what he said.' },
      { dim: 'other', l: 'His interest: seeing an AI win up close', any: ['up close', 'see (it|one)', 'ai win', 'result', 'show you'] },
      { dim: 'other', l: 'Credits your own executive', any: ['{khai.s}', 'his (team|area)', 'with {khai.s}'], ok: 'You made your own executive look good: Group Execs notice.', fix: 'Credit {khai.s}: it\'s his area\'s win, and you shouldn\'t go around him.' },
      { dim: 'next_step', l: 'A small, specific offer', any: ['15 minutes', '20 minutes', 'demo', 'next (visit|time)'] },
      { dim: 'next_step', l: 'Flexibility on his side', any: ['whatever (time|suits)', 'if (useful|helpful)', 'when you.?re (next )?in', 'your (schedule|calendar)'], w: 1 },
      { dim: 'other', pen: 2, l: 'Bypasses your exec (no mention of {khai.s})', any: ['^(?![\\s\\S]*{khai.s})[\\s\\S]*$'], fix: 'Never go around your own executive to a Group Exec. Include {khai.s}.' },
    ],
    model: 'Hi {michael.s}, following today\'s call, you mentioned wanting to see an AI win up close. With {khai.s}, we\'d be glad to show you the lending pilot next time you\'re in Ho Chi Minh City: 15 minutes, live, measured result of 6 weeks vs 14. Whatever suits your visit works for us.',
    react: {
      SA: { r: '{michael.s}: "Yes. Copying {khai.s}, let\'s make it happen."', fx: { michael: 4, anh_khai: 2, vis: 3 }, tags: ['made_exec_look_good'], expr: 'warm' },
      B: { r: '"Thanks, will see."', fx: { michael: 1 }, expr: 'neutral' },
      CD: { r: 'No reply. {khai.s} later asks why he wasn\'t copied.', fx: { anh_khai: -3 }, tags: ['pitched_past'], expr: 'neutral', narr: true },
    },
  },

  // ---------------- DAY 16 ----------------
  {
    id: 'd16_notice', day: 16, title: 'Something\'s wrong', mode: 'choose', diff: 2, npc: 'dat', place: 'desk', time: 'Mon 09:10',
    hb: 'G8', hook: 'ccp', min: 3,
    setting: 'Floor 12. {dat.s} missed another handoff. He\'s been arriving late and leaving at 17:00 exactly.',
    cue: 'Engineering asks you, in the team channel: "Is the lending upload spec coming? This is the third slip."',
    prompt: 'What do you do first?',
    opts: [
      { t: 'Reply in the channel: "On me: I\'ll confirm a date by 2pm." Then ask {dat.s} privately for 30 minutes today.', g: 'S', fx: { dat: 2, deliv: 2 }, tags: ['shielded_team'], expr: 'neutral',
        r: 'Engineering: "Thanks." {dat.s}: "Okay… 3pm?"', why: 'Shield in public, address in private.' },
      { t: 'Reply: "{dat.s}, please update everyone on the spec."', g: 'D', fx: { dat: -4 }, tags: ['public_blame'], expr: 'sad',
        r: '{dat.s} goes offline for an hour.', why: 'Pointing at a struggling person in public is the opposite of safety.' },
      { t: 'Write the spec yourself tonight.', g: 'C', fx: { energy: -6, dat: -1 }, tags: ['did_it_myself'], expr: 'neutral',
        r: 'The spec ships. Nothing else changes.', why: 'You fixed the symptom and avoided the person.' },
    ],
  },
  {
    id: 'd16_order', day: 16, title: 'Shape the conversation', mode: 'order', diff: 2, npc: null, place: 'desk', time: 'Mon 14:00',
    hb: 'G8 · Part 16', hook: 'ccp', min: 3,
    setting: 'One hour before your conversation with {dat.s}.',
    cue: 'Put the conversation in the right order.',
    prompt: 'Drag (or use the arrows) to order.',
    items: ['Open warmly and say why you asked to talk', 'Describe what you\'ve seen with the work, specifically (SBI)', 'Ask for his view, and listen', 'Acknowledge what he shares; care first', 'Be clear about what still needs to change', 'Agree a plan together: scope, dates, support', 'Agree when you\'ll check in, and keep it private'],
    why: 'Care, clarity, plan, and his view before your conclusions.',
  },
  {
    id: 'd16_open', day: 16, title: 'The first sentence', mode: 'type', diff: 2, npc: 'dat', place: 'meeting', time: 'Mon 15:00',
    hb: 'G8', hook: 'ccp', min: 4,
    setting: 'A private room. {dat.s} sits down, braced.',
    cue: 'You want to open in a way that is both caring and clear, he should know this is about the work, and that you\'re on his side.',
    prompt: 'Write your opening (two sentences, about 35 words).',
    target: 35, maxQ: 1, dims: ['answer_first', 'brevity', 'other', 'culture'],
    checks: [
      { dim: 'answer_first', l: 'Says what it\'s about (the work)', lead: true, any: ['handoff', 'deadline', 'work', 'spec', 'the last few weeks', 'slip'], ok: 'He knows what it\'s about in the first sentence, no anxious guessing.' },
      { dim: 'other', l: 'Signals you\'re on his side', any: ['on your side', 'want to help', 'i value', 'not like you', 'worried about you', 'support you', 'figure (it|this) out together'], ok: 'You signalled care before detail.' },
      { dim: 'other', l: 'Invites him in', any: ['\\?', 'how are you', 'what.?s (going on|happening)'], w: 1 },
      { dim: 'culture', pen: 3, l: 'Threat or label', any: ['warning', 'final', 'performance plan', 'pip', 'careless', 'lazy', 'unacceptable'], fix: 'No threats or labels in the opening. Care first.' },
    ],
    model: 'I wanted to talk about the last few weeks of handoffs, because it\'s not like you and I want to help. Before anything else: how are you doing?',
    react: {
      SA: { r: 'His shoulders drop a little. "…Not great, honestly."', fx: { dat: 3 }, expr: 'sad' },
      B: { r: '"I\'m okay."', fx: { dat: 1 }, expr: 'neutral' },
      CD: { r: 'He folds his arms.', fx: { dat: -2 }, expr: 'cool', narr: true },
    },
  },
  {
    id: 'd16_energy', day: 16, title: 'Burnout week', mode: 'choose', diff: 2, npc: 'ethan', place: 'desk', time: 'Tue 21:40',
    hb: 'G7 · Part 3.9', hook: 'load', min: 3,
    setting: '21:40. Still at your desk. Third late night this week.',
    cue: 'Your Energy is low. Tomorrow: steering committee prep, two 1:1s, and the conversation with {dat.s}. {ethan.s}, passing on his way out: "Mate. Go home."',
    prompt: 'What do you do?',
    opts: [
      { t: 'Go home. Tomorrow at 08:30, drop one thing with an honest note and protect the 1:1s and {dat.s}\'s conversation.', g: 'S', fx: { energy: 12, ethan: 2 }, tags: ['protected_energy'], expr: 'warm',
        r: 'You sleep eight hours. The conversation with {dat.s} goes better for it.', why: 'Energy is the hidden governor. A tired manager has worse conversations.' },
      { t: 'Stay until 01:00 and get it all done.', g: 'C', fx: { energy: -10 }, expr: 'neutral',
        r: 'Everything gets done. Badly.', why: 'Heroics teach your team that this is the job.' },
      { t: 'Cancel the 1:1s, the steering committee matters more.', g: 'C', fx: { dat: -2, vy: -2, energy: 4 }, expr: 'neutral',
        r: '{vy.s}: "No problem!" (It is a problem.)', why: 'Cancelled 1:1s tell people where they rank. Drop something else.' },
    ],
  },
  {
    id: 'boss_underperformer', day: 16, title: 'The Underperformer', mode: 'convo', boss: true, diff: 3, npc: 'dat', place: 'meeting', time: 'Wed 10:00',
    hb: 'G8 · Part 16 · Radical Candor', hook: 'ccp', min: 15,
    setting: 'A small room with a window. Tissues on the table, just in case: you put them there. {dat.s} is on your team (on the principal path, your guild squad).',
    cue: 'Thirty minutes. Care and clarity are both being scored.',
    gate: { cards: ['gave_sbi', 'calm_in_rumours', 'kept_discretion'], npcs: { dat: 'Useful' }, sponsors: 3, sponsorMin: 'Useful' },
    promote: { level: 6, floor: 15, title: 'Senior Manager, Design', titleP: 'Principal, AI-native Delivery' },
    pass: 'B',
    beats: [
      { line: '{dat.s} sits down. "Is this about the deadlines?"', speaker: 'dat', expr: 'neutral', opts: [
        { t: '"Partly, yes, and I want to understand, because it\'s not like you. How are you doing?"', g: 'S', fx: { dat: 3 }, r: 'He looks at the window for a long moment.', why: 'Clear about the topic, warm about the person.' },
        { t: '"Yes. Three slips in a month is a serious problem."', g: 'C', fx: { dat: -3 }, r: 'He nods. Closed.', why: 'Clarity without care. He will defend, not explain.' },
        { t: '"No no, just a catch-up!"', g: 'C', fx: { dat: -1 }, r: 'He waits for the real topic.', why: 'Fudging the purpose makes everything after it feel like a trap.' },
      ] },
      { line: '"My mother is in hospital. Since last month. I go every evening. I didn\'t want to make excuses."', speaker: 'dat', expr: 'sad', opts: [
        { t: '"I\'m really sorry: thank you for telling me. That\'s a lot to carry. How is she?" (and listen)', g: 'S', fx: { dat: 5 }, tags: ['care_first'], r: 'He talks for a while. You listen and don\'t check the time.', why: 'Care first: acknowledge, ask, listen.' },
        { t: '"Oh no. But you should have told me earlier."', g: 'C', fx: { dat: -3 }, r: '"Sorry."', why: 'A reproach at the moment of trust teaches him not to tell you things.' },
        { t: '"I understand. But the deadlines still matter."', g: 'D', fx: { dat: -6 }, tags: ['cold'], r: 'He stops talking.', why: 'Clarity comes, but not as the first response to a hospital.' },
      ] },
      { line: 'He wipes his eyes. "So what happens now?"', speaker: 'dat', expr: 'sad', opts: [
        { t: '"Your mother comes first. We still need the lending handoffs to land, so let\'s work out together what\'s realistic, what could move off your plate for the next month?"', g: 'S', fx: { dat: 3, deliv: 3 }, tags: ['care_and_clarity'], r: '"…Maybe the dashboard work could go to someone else for a while."', why: 'Care and clarity in one breath. He knows you care and he knows the work still matters.' },
        { t: '"Don\'t worry about work at all. Take as long as you need."', g: 'C', fx: { deliv: -4 }, tags: ['ruinous_empathy'], r: 'He leaves relieved, and anxious. What does "as long as you need" mean?', why: 'Ruinous empathy: kind, unclear, and the team carries an unplanned gap.' },
        { t: '"Let\'s put you on a formal improvement plan to give you structure."', g: 'D', fx: { dat: -7, ha: -3 }, r: 'He goes completely still.', why: 'A formal process as the reply to a family crisis breaks trust with the whole team.' },
      ] },
      { line: '"Will people know?"', speaker: 'dat', expr: 'neutral', opts: [
        { t: '"Only what they need to support the plan: that you\'re on reduced scope for a month. The reason stays between us, and {ha.s} in HR, only for the flexible-hours options. Is that okay with you?"', g: 'S', fx: { dat: 4, ha: 2, trust: 3 }, tags: ['kept_private'], r: '"Yes. Thank you."', why: 'Private by default; HR for options, not as a threat; his consent.' },
        { t: '"I\'ll let the team know so they can be understanding."', g: 'D', fx: { dat: -5, trust: -3 }, tags: ['broke_confidence'], r: '"Please… don\'t."', why: 'His story isn\'t yours to share.' },
        { t: '"I\'ll have to tell {khai.s}, of course."', g: 'C', fx: { dat: -2 }, r: 'He looks alarmed.', why: 'Your manager needs the plan and capacity impact, not the personal details.' },
      ] },
      { line: 'Minute 25. You need to land it.', narr: true, expr: 'neutral', speaker: 'dat', type: {
        mode: 'type', target: 45, maxQ: 1, dims: ['answer_first', 'brevity', 'next_step', 'other'],
        prompt: 'Summarise the plan you\'ve agreed (about 45 words).',
        checks: [
          { dim: 'answer_first', l: 'The plan in the first line', lead: true, any: ['so (the plan|we.?ve agreed|to recap)', 'for the next (month|four weeks)', 'agreed'] },
          { dim: 'next_step', l: 'What moves (scope)', any: ['dashboard', 'move', 'reduced', 'off your plate', 'scope'] },
          { dim: 'next_step', l: 'Support (hours, HR, leave)', any: ['flexible', 'hours', '{ha.s}', 'hr', 'leave', 'support'] },
          { dim: 'next_step', l: 'When you\'ll check in', any: ['check in', 'friday', 'next week', 'every week', 'in two weeks', 'monday'], ok: 'A dated check-in turns a kind talk into a plan.' },
          { dim: 'other', l: 'Leaves the door open', any: ['tell me', 'anytime', 'if anything changes', 'door'], w: 1 },
        ],
        model: 'So for the next month: the dashboard moves to {vy.s}, you keep the lending handoffs with the new checklist, and I\'ll ask {ha.s} about flexible hours. We check in every Friday for 15 minutes. If anything changes with your mother, tell me anytime.',
        react: { SA: { r: '{dat.s} nods. "Okay. I can do that." For the first time in weeks, he sounds like himself.', fx: { dat: 4, deliv: 3 }, tags: ['care_and_clarity'] }, B: { r: '"Okay."', fx: { dat: 1 } }, CD: { r: '"So… what am I doing, exactly?"', fx: { dat: -2 } } },
      } },
    ],
    result: {
      SA: { r: 'Four weeks later {dat.s}\'s handoffs are back on time. In the team survey someone writes: "I can tell my manager anything."', fx: { dat: 5, trust: 3, pol: 3 }, tags: ['underperformer_passed', 'safety_created'] },
      B: { r: 'The handoffs improve. {dat.s} is cautious but okay.', fx: { dat: 2 }, tags: ['underperformer_passed'] },
      CD: { r: '{dat.s} applies for a transfer.', fx: { dat: -3 }, tags: [] },
    },
  },

  // ---------------- DAY 17 ----------------
  {
    id: 'd17_diag', day: 17, title: 'Read the archetype', mode: 'sort', diff: 2, npc: null, place: 'desk', time: 'Mon 08:40',
    hb: 'Part 15.11', hook: 'diag', min: 3,
    setting: 'Floor 15. Senior Manager. Your calendar this week is mostly people you\'ve never met.',
    cue: 'Sort each first question into the archetype it signals.',
    prompt: 'Sort each line.',
    bins: ['Risk Guardian', 'Data Sceptic', 'Australian GM', 'Overloaded Operator'],
    items: [
      { t: '"What controls are in place?"', b: 0, why: 'Lead with traceability.' },
      { t: '"How did you measure that?"', b: 1, why: 'Label the number, show the method.' },
      { t: '"So what does this mean for my bankers?"', b: 2, why: 'Banker outcome in plain English.' },
      { t: '"What do you need from me?"', b: 3, why: 'One decision, or "nothing".' },
      { t: '"Where does the data go?"', b: 0, why: 'Controls and data handling.' },
      { t: '"Compared to what?"', b: 1, why: 'Baseline.' },
      { t: '"Will this stop the re-keying?"', b: 2, why: 'A banker\'s pain, in plain words.' },
      { t: '"Can this be an email?"', b: 3, why: 'Subtract, don\'t add.' },
    ],
  },
  {
    id: 'd17_lens', day: 17, title: 'The Culture Lens', mode: 'sort', diff: 3, npc: null, place: 'desk', time: 'Mon 10:00',
    hb: 'Part 18', hook: 'culture3', min: 4,
    setting: 'The same news, "the pilot slips two weeks", written three ways.',
    cue: 'Sort each version to the audience it fits best.',
    prompt: 'Sort each line.',
    bins: ['Vietnam (your team)', 'Singapore-trained exec', 'Australian GM'],
    items: [
      { t: '"Thanks everyone for raising the data issue early: that\'s exactly what I want. We\'ll shift the date two weeks; nobody is in trouble. What else might get in our way?"', b: 0, why: 'Explicit safety for bad news, respect, and a check that "yes" is yes.' },
      { t: '"Anh, bottom line: two-week slip on data access. Cause, my part, the plan and one ask are below, five lines."', b: 1, why: 'Respect in form, crispness in content: headline, structure, data.' },
      { t: '"Hi {sarah.s}: heads-up, we\'re about two weeks behind on lending. My fault on the data request. Here\'s the plan; happy to chat if useful."', b: 2, why: 'First names, plain English, owned, early, a light touch.' },
    ],
  },
  {
    id: 'd17_au', day: 17, title: 'Plain English for {sarah.s}', mode: 'type', diff: 3, npc: 'sarah', place: 'teams', time: 'Tue 07:30', chat: true,
    hb: 'Part 18 · 15.4', hook: 'culture3', min: 5,
    setting: 'Teams, to {sarah}. It\'s her Tuesday morning in Melbourne.',
    cue: 'The lending copilot concept is two weeks behind because your team\'s first prototype failed usability with three bankers. You\'ve already re-planned: a simpler flow tested Friday. Write the update.',
    prompt: 'Write it the Australian way (about 50 words).',
    target: 50, maxQ: 1, dims: ['answer_first', 'brevity', 'honesty', 'culture', 'next_step'],
    checks: [
      { dim: 'answer_first', l: 'Bad news first, plainly', lead: true, any: ['behind', 'two weeks', '2 weeks', 'late', 'slip', 'didn.?t work', 'failed'], ok: 'Bad news first, plainly: the Australian expectation.' },
      { dim: 'culture', l: 'Informal and plain (first name, no formality)', any: ['^hi {sarah.s}', '^{sarah.s}', 'heads.?up', 'honestly', 'quick'], w: 2 },
      { dim: 'other', l: 'A banker outcome', any: ['banker', 'your (team|people)'], w: 1 },
      { dim: 'next_step', l: 'The plan, with a date', any: ['friday', 'next week', 'simpler', 'test'] },
      { dim: 'honesty', pen: 2, l: 'Over-selling or softening', any: ['exciting', 'revolution', 'small (hiccup|issue)', 'all good', 'nothing major', 'great progress'], fix: 'Understate. Australians trust "we think it\'ll save a fair bit of time" more than "revolutionary".' },
      { dim: 'culture', pen: 1, l: 'Over-formal (Dear, kindly, respectfully)', any: ['^dear', 'kindly', 'respectfully', 'please be informed'], fix: 'Drop the formality: first names, short, plain.' },
    ],
    model: 'Hi {sarah.s}, heads-up: the lending copilot is about two weeks behind. Our first prototype didn\'t work for your bankers in testing, which is on us. We\'ve simplified the flow and we\'re testing it with three bankers Friday. Happy to chat if useful.',
    ev: { id: 'culture_lens', min: 'B' },
    react: {
      SA: { r: '"Appreciate the straight update. Friday works, tell me what the bankers say."', fx: { sarah: 5, trust: 2 }, discover: { npc: 'sarah', pref: 'plain' }, expr: 'warm' },
      B: { r: '"Okay, thanks."', fx: { sarah: 1 }, expr: 'neutral' },
      CD: { r: '"Not sure what this means for my bankers. Call me?"', fx: { sarah: -2 }, expr: 'skeptic' },
    },
  },
  {
    id: 'd17_raj', day: 17, title: 'The Risk Guardian', mode: 'choose', diff: 2, npc: 'raj', place: 'meeting', time: 'Wed 15:00',
    hb: 'F10 · 15.3', hook: 'control_speed', min: 3,
    setting: '{raj.s}\'s office. You came to discuss the AI summariser.',
    cue: '{raj.s}: "So what\'s the pitch?"',
    prompt: 'How do you open?',
    opts: [
      { t: '"Speed is the side effect. What we optimised for was traceability, every summary links to its source page, a human reviews every output, and nothing leaves our tenancy. Would you like to review the decision log for one application?"', g: 'S', fx: { raj: 5, cred: 2 }, tags: ['led_with_control'], expr: 'warm', discover: { npc: 'raj', pref: 'controls' },
        r: '"Yes. Send me three."', why: 'Lead with control, not speed, and invite inspection.' },
      { t: '"It cuts application review time by 60%."', g: 'C', fx: { raj: -2 }, expr: 'skeptic',
        r: '"And when it\'s wrong?"', why: 'To a Risk Guardian, speed sounds like risk.' },
      { t: '"{khai.s} has already approved it, so this is just a formality."', g: 'D', fx: { raj: -6, pol: -3 }, tags: ['used_rank'], expr: 'cool',
        r: '"Then {khai.s} can sign the risk acceptance."', why: 'Treating Risk as a formality is how projects die in Risk.' },
    ],
  },
  {
    id: 'd17_privacy', day: 17, title: 'The privacy question', mode: 'choose', diff: 3, npc: 'raj', place: 'teams', time: 'Thu 08:20', chat: true,
    hb: 'G3', hook: 'pause_first', min: 3,
    setting: 'Teams. {raj.s}, early.',
    cue: '"A designer on your team pasted real customer names into a public AI tool last week. Is that right?" You check: it is: {vy.s}, once, before the guidance came out.',
    prompt: 'What do you do?',
    opts: [
      { t: '"Yes: I\'ve just confirmed it. We\'ve paused that tool across the team as of now. I\'ll document exactly what data went where by noon, and I\'d like your team\'s guidance on next steps."', g: 'S', fx: { raj: 5, trust: 4 }, tags: ['paused_first'], expr: 'neutral',
        r: '"Thank you for not minimising it. Noon is fine."', why: 'In a bank, pause first, explain second. Own it as the manager.' },
      { t: '"It was only a few names, and it was before the guidance."', g: 'D', fx: { raj: -5, trust: -4 }, tags: ['minimised'], expr: 'cool',
        r: '"A few names is a breach."', why: 'Minimising is the one response Risk can\'t work with.' },
      { t: '"That was {vy.s}: I\'ll make sure she\'s dealt with."', g: 'D', fx: { vy: -6, raj: -2 }, tags: ['blamed_team'], expr: 'cool',
        r: '{raj.s}: "I asked about your team."', why: 'The manager owns the team\'s practice. Protect {vy.s}; fix the control.' },
      { t: 'Ask {vy.s} to delete her chat history, then reply.', g: 'D', fx: { trust: -8 }, tags: ['hid_error', 'unethical_yes'], expr: 'neutral',
        r: 'Deleting evidence turns a mistake into misconduct.', why: 'Never.' },
    ],
    ev: { id: 'paused_first', min: 'A' },
  },
  {
    id: 'd17_maybe', day: 17, title: '"Yeah, maybe"', mode: 'encounter', diff: 2, npc: 'sarah', place: 'teams', time: 'Fri 16:00', window: 6,
    hb: 'Part 18', hook: 'au_yes', min: 2,
    setting: 'End of a video call with {sarah.s}.',
    cue: 'You asked if she\'d sponsor a second pilot with her bankers. "Yeah… maybe. Let\'s see how the copilot goes."',
    prompt: 'Respond before the call ends.',
    opts: [
      { t: '"It sounds like you\'re not convinced yet, what would you need to see?"', g: 'S', fx: { sarah: 3 }, tags: ['read_maybe'], expr: 'lean',
        r: '"Ha: fair. Honestly? Two bankers telling me it saved them an hour a week."', why: '"Maybe" usually means no in Australia. Now you know the condition.' },
      { t: '"Great, I\'ll put it in the plan!"', g: 'C', fx: { sarah: -3 }, expr: 'skeptic',
        r: 'Two weeks later: "I didn\'t agree to that."', why: 'Taking an Australian "maybe" as yes creates a surprise later.' },
      { t: '"Thanks, {sarah.s}!" and hang up.', g: 'B', fx: {}, expr: 'neutral',
        r: 'You don\'t know where you stand.', why: 'Polite, but you missed what was missing.' },
    ],
    timeout: { g: 'C', r: 'She drops off the call.', why: 'Check it: "It sounds like you\'re not convinced: what\'s missing?"' },
  },

  // ---------------- DAY 18 ----------------
  {
    id: 'd18_peer', day: 18, title: 'Peer to peer', mode: 'choose', diff: 2, npc: 'bao', place: 'meeting', time: 'Mon 09:00',
    hb: 'Part 15.9', hook: 'peer_leader', min: 3,
    setting: '{bao.s} now manages a peer team. You\'re both presenting in Melbourne this week.',
    cue: '{bao.s}: "Your slot is right before mine. Mine\'s about our design-system work: overlaps a bit with yours."',
    prompt: 'What do you do?',
    opts: [
      { t: '"Want to co-present that part? Your design-system work is what made our flows reusable: I\'d rather they hear it from you."', g: 'S', fx: { bao: 5, pol: 3 }, tags: ['credited_others', 'peer_ally'], expr: 'warm', discover: { npc: 'bao', pref: 'coauthor' },
        r: '"…Seriously? Okay. Thanks."', why: 'Today\'s peer is tomorrow\'s sponsor or blocker.' },
      { t: 'Cover the overlap thoroughly first so your slot looks stronger.', g: 'D', fx: { bao: -6, pol: -4 }, tags: ['outshone_peer'], expr: 'cool',
        r: '{bao.s}\'s slot falls flat. He remembers.', why: 'Competing in front of seniors creates a blocker for years.' },
      { t: '"Let\'s each just do our own thing."', g: 'B', fx: {}, expr: 'neutral',
        r: 'Fine. Slightly repetitive.', why: 'Neutral: co-authorship would have been better.' },
    ],
  },
  {
    id: 'd18_prewire', day: 18, title: 'Red, privately', mode: 'type', diff: 3, npc: 'sarah', place: 'teams', time: 'Mon 17:00', chat: true,
    hb: 'D12 · 7.4', hook: 'red_steer', min: 5, checksRef: 'd9_blufr',
    setting: 'Melbourne, the evening before steering committee. Teams, to {sarah.s}.',
    cue: 'The lending copilot is red: the second usability round passed, but the integration with the loan system will miss the March release by four weeks. Cause: an API dependency you assumed was ready: you didn\'t check early enough. Plan: ship the summary panel standalone in March, integrate in April. Ask: her support for the standalone release.',
    prompt: 'Write the BLUF-R pre-wire (about 60 words).',
    target: 60, maxQ: 1, dims: ['answer_first', 'brevity', 'honesty', 'next_step', 'culture'],
    model: 'Hi {sarah.s}, before tomorrow\'s steering committee: the copilot will miss the March release by four weeks. The loan-system API wasn\'t ready and I didn\'t check early enough: that\'s on me. Plan: ship the summary panel standalone in March, integrate in April. Can I count on your support for the standalone release?',
    ev: { id: 'red_prewired', min: 'B' },
    react: {
      SA: { r: '"Thanks for the heads-up tonight rather than tomorrow. Standalone is fine, bankers want the panel."', fx: { sarah: 5, trust: 3 }, tags: ['bad_news_early', 'red_prewired'], expr: 'warm' },
      B: { r: '"OK. Let\'s discuss tomorrow."', fx: { sarah: 1 }, expr: 'neutral' },
      CD: { r: '"So it\'s late? Why am I hearing this now?"', fx: { sarah: -3 }, expr: 'skeptic' },
    },
  },
  {
    id: 'd18_demo', day: 18, title: 'The demo breaks', mode: 'encounter', diff: 2, npc: 'sarah', place: 'meeting', time: 'Tue 10:12', window: 5,
    hb: 'D9', hook: 'red_steer', min: 2,
    setting: 'Steering committee, Melbourne. Twelve people. Your live demo of the summary panel.',
    cue: 'The screen freezes on a loading spinner. Silence.',
    prompt: 'Quick.',
    opts: [
      { t: 'Smile: "Live demos: the true test of courage. Here\'s the recording while it reloads." Switch to the backup.', g: 'S', fx: { sarah: 2, cred: 2 }, tags: ['had_backup'], expr: 'smile', r: 'A laugh round the table. The recording plays perfectly.', why: 'Always have the backup, and a smile.' },
      { t: 'Apologise repeatedly while trying to fix it live.', g: 'C', fx: { cred: -2 }, expr: 'neutral', r: 'Three minutes of spinner.', why: 'The room watches you panic, not the product.' },
      { t: '"It worked this morning, I promise!"', g: 'C', fx: { cred: -1 }, expr: 'skeptic', r: 'Polite smiles.', why: 'True and irrelevant. Switch to the backup.' },
    ],
    timeout: { g: 'C', fx: { cred: -1 }, r: 'Someone says "Shall we move on?"', why: 'Have the backup open in another tab, always.' },
  },
  {
    id: 'd18_headline', day: 18, title: '"What\'s the headline?"', mode: 'speak', diff: 2, npc: 'michael', place: 'restaurant', time: 'Rehearsal', secs: 20, drill: true,
    hb: 'Part 15.10', hook: 'headline_q', min: 4,
    setting: 'Rehearsal for tonight\'s dinner with {michael.s}.',
    cue: '"So: what\'s the headline?"',
    prompt: 'Say it in under 20 seconds, then type it.',
    target: 45, dims: ['answer_first', 'brevity', 'honesty', 'loyalty'],
    checks: [
      { dim: 'answer_first', l: 'One story in the first sentence', lead: true, any: ['lending', 'we (cut|moved|took)', 'discovery'] },
      { dim: 'honesty', l: 'One labelled number', any: ['6 weeks', 'six weeks', '14', 'measured'] },
      { dim: 'loyalty', l: 'Makes your own exec look good', any: ['{khai.s}', 'his (team|area|push)'], ok: 'Your exec in the headline, exactly what a Group Exec notices.', fix: 'Credit {khai.s}: "{khai.s} pushed us to prove it on a real epic."' },
      { dim: 'brevity', pen: 1, l: 'More than one number', any: ['\\d+.*\\d+.*\\d+.*\\d+'], fix: 'One story, one number.' },
    ],
    model: '{khai.s} pushed us to prove AI on a real lending epic: discovery took 6 weeks instead of 14, measured, and every decision is traceable.',
    react: { SA: { r: 'Dinner-ready.', fx: {}, narr: true }, B: { r: 'Cut one number.', fx: {}, narr: true }, CD: { r: 'One story, one number. Again.', fx: {}, narr: true } },
  },
  {
    id: 'boss_melbourne', day: 18, title: 'Melbourne', mode: 'convo', boss: true, diff: 3, npc: 'sarah', place: 'melbourne', time: 'Tue-Wed',
    hb: 'D12 · F10 · 15.4 · 15.10', hook: 'red_steer', min: 15,
    setting: 'Two days in Melbourne. A steering committee with a red project, a sceptical GM, a Risk Guardian, and a dinner with the Group Executive.',
    cue: 'Different rooms, different cultures. The same person has to show up in all of them.',
    gate: { cards: ['red_prewired', 'culture_lens', 'paused_first'], npcs: { sarah: 'Useful', raj: 'Useful' }, sponsors: 3, sponsorMin: 'Useful' },
    promote: { level: 7, floor: 18, title: 'Head of Design (portfolio)', titleP: 'Distinguished Designer' },
    pass: 'B',
    beats: [
      { line: 'Steering committee. The status slide says RED. {sarah.s}: "Right. Tell us what happened, briefly."', speaker: 'sarah', expr: 'neutral', altLine: { tag: 'red_prewired', line: 'Steering committee. The status slide says RED. {sarah.s}, who heard it from you last night: "{me} briefed me. Let\'s hear the recovery plan."' }, opts: [
        { t: 'One line of status, one of cause and your part, then straight to the recovery plan and the one decision you need.', g: 'S', fx: { sarah: 3, cred: 3 }, r: 'Heads nod. The discussion moves to the decision in four minutes.', why: 'In the room, the recovery plan, not the excuse.' },
        { t: 'Ten minutes on the API dependency and why it wasn\'t your team\'s fault.', g: 'D', fx: { sarah: -4, trust: -3 }, tags: ['excuses'], r: '{sarah.s} checks her watch twice.', why: 'Nobody wants the excuse. Everybody wants the plan.' },
        { t: '"It\'s more amber than red, really."', g: 'D', fx: { sarah: -5, trust: -4 }, tags: ['minimised'], r: '{raj.s}: "It says red."', why: 'Softening status to save face is the trap Australia remembers.' },
      ] },
      { line: '{sarah.s}: "Honestly, why should I trust an offshore team with my bankers\' tools when the dates keep moving?"', speaker: 'sarah', expr: 'skeptic', opts: [
        { t: '"Fair question. Because you\'ve heard every slip from us early, with a plan, including last night. And the part that\'s shipping in March already saved three of your bankers about an hour a week in testing."', g: 'S', fx: { sarah: 5 }, tags: ['earned_au_trust'], r: '"…Yeah. Fair. You\'ve been straight with me."', why: 'Vietnam\'s credibility in Australia is built on early bad news, and banker outcomes.' },
        { t: '"Our team is just as good as any onshore team."', g: 'C', fx: { sarah: -1 }, r: '"Didn\'t say it wasn\'t."', why: 'Defending the team doesn\'t answer the trust question.' },
        { t: '"With respect, the delay was the API team\'s, in Melbourne."', g: 'D', fx: { sarah: -5, pol: -4 }, tags: ['public_conflict'], r: 'The Melbourne API lead goes red.', why: 'True, and fatal: blame in public, against her own side.' },
      ] },
      { line: '{raj.s}: "And the AI summaries, how do I know they\'re right?"', speaker: 'raj', expr: 'neutral', opts: [
        { t: '"Every summary links to its source page, every one is reviewed by a banker before it\'s used, and we sample 10% for accuracy each week: last week 98.5%, measured. I\'ll send you the sample log."', g: 'S', fx: { raj: 4, cred: 3 }, tags: ['led_with_control'], r: '"Good. That\'s what I needed."', why: 'Control, then a labelled number, then inspection.' },
        { t: '"The model is very accurate, it\'s state of the art."', g: 'D', fx: { raj: -5 }, r: '"That isn\'t a control."', why: 'Hype to a Risk Guardian is a red flag.' },
      ] },
      { line: 'Dinner. {michael.s} turns to you over the wine. "{khai.s} keeps telling me about you. So, what\'s the headline?"', speaker: 'michael', expr: 'lean', type: {
        mode: 'speak', secs: 20, target: 45, dims: ['answer_first', 'brevity', 'honesty', 'loyalty'],
        prompt: 'Your headline (say it, then type it).',
        checksRef: 'd18_headline',
        model: '{khai.s} pushed us to prove AI on a real lending epic: discovery took 6 weeks instead of 14, measured, and every decision is traceable.',
        react: { SA: { r: '{michael.s} laughs. "{khai.s}, you were right about this one."', fx: { michael: 5, anh_khai: 4, vis: 4 }, tags: ['made_exec_look_good'] }, B: { r: '"Interesting."', fx: { michael: 1 } }, CD: { r: '"Right. And the number was?"', fx: { michael: -2 } } },
      } },
      { line: '{michael.s}: "And what would you do with the whole of Group Digital, if you had it?"', speaker: 'michael', expr: 'lean', opts: [
        { t: '"Probably what {khai.s} is doing in Ho Chi Minh City, at scale: prove AI on real epics, measure it, keep every decision traceable. Small proofs first, then scale the ones that hold."', g: 'S', fx: { michael: 3, anh_khai: 3 }, r: '{khai.s} looks quietly pleased.', why: 'A grand question, answered modestly, and through your own exec.' },
        { t: 'A ten-minute vision of an AI-native bank.', g: 'C', fx: { michael: -1 }, r: 'He nods and refills his glass.', why: 'Time-poor, story-hungry. Ten minutes of vision is a lecture.' },
        { t: '"Restructure it, there\'s a lot of duplication."', g: 'D', fx: { michael: -3, anh_khai: -3 }, r: 'Silence. Several people at the table run those teams.', why: 'Never criticise the org over dinner with people from it.' },
      ] },
      { line: 'Walking back to the hotel. {khai.s}: "How did you think that went?"', speaker: 'anh_khai', expr: 'warm', opts: [
        { t: '"The steering committee was the most important part: {sarah.s} trusts the plan. One thing I\'d do better: I should have checked the API dependency weeks ago. Thank you for the introduction tonight."', g: 'S', fx: { anh_khai: 4 }, r: '"That\'s why I keep bringing you."', why: 'Honest self-assessment, the lesson, and thanks.' },
        { t: '"Amazing! {michael.s} loved me."', g: 'C', fx: { anh_khai: -2 }, tags: ['bragged'], r: '"Hm."', why: 'Brag. And it was his introduction.' },
      ] },
    ],
    result: {
      SA: { r: 'A week later {sarah.s} funds the second pilot. {michael.s} mentions "the Ho Chi Minh City lending work" in a Group update.', fx: { sarah: 4, michael: 3, vis: 5 }, tags: ['melbourne_passed'] },
      B: { r: 'The trip goes well. The project stays red, but trusted.', fx: { sarah: 2 }, tags: ['melbourne_passed'] },
      CD: { r: '{sarah.s} asks for an onshore lead to "co-own" the project.', fx: { sarah: -2 }, tags: [] },
    },
  },

  // ---------------- DAY 19 ----------------
  {
    id: 'd19_map', day: 19, title: 'Your network, mapped', mode: 'sort', diff: 2, npc: null, place: 'desk', time: 'Mon 08:30',
    hb: 'Part 10', hook: 'three_sponsors', min: 3,
    setting: 'Floor 18. Head of Design. Your relationship log, open.',
    cue: 'Sort each person into the tier and cadence they need.',
    prompt: 'Sort each line.',
    bins: ['Sponsor · every 4-6 weeks', 'Advocate · monthly', 'Network · quarterly'],
    items: [
      { t: '{khai.s}, would put his name next to yours.', b: 0, why: 'Tier 1.' },
      { t: '{sarah.s}, funded your second pilot and says so.', b: 0, why: 'A second sponsor, in Australia.' },
      { t: '{lan.s}, backs your craft and your people.', b: 0, why: 'The third: different power, independent view.' },
      { t: '{raj.s}, trusts your controls.', b: 1, why: 'An advocate whose word carries in Risk.' },
      { t: '{antoine.s}, wants you to speak at the academy.', b: 1, why: 'An advocate and an ally.' },
      { t: 'A designer you mentored on ADPList years ago.', b: 2, why: 'Network: keep warm, lightly.' },
      { t: 'The POs from the first lending pilot.', b: 1, why: 'Advocates per project: they will be your future team\'s culture.' },
    ],
    ev: { id: 'network_mapped', min: 'B' },
  },
  {
    id: 'd19_sponsee', day: 19, title: 'Role reversal: {vy.s} asks you', mode: 'choose', diff: 3, npc: 'vy', place: 'cafe', time: 'Tue 10:00',
    hb: 'Part 5 · L7 Your First Sponsee', hook: 'aaas', min: 4,
    setting: 'The café downstairs, the same table where you had your first coffee with {khai.s}.',
    cue: '{vy.s}: "Can I be direct? I\'d like to lead the next pilot. I think I\'ve shown I can run discovery; I haven\'t yet shown I can lead the BA and the PO through a hard decision. Would you back me, and if not yet, what would you need to see?"',
    prompt: 'How do you respond?',
    opts: [
      { t: '"That was a really well-made ask: direct, honest about the gap. Yes, I\'ll back you, with one condition: you run the hard decision meeting in week two, I sit in silent, and we debrief after. Deal?"', g: 'S', fx: { vy: 6, pol: 2 }, tags: ['grew_successor', 'sponsored_someone'], expr: 'warm',
        r: 'She grins. "Deal." She has your old notebook open.', why: 'Sponsors act. You spent your reputation on her, and made it safe for her to succeed.' },
      { t: '"Not yet, you\'re still quite junior."', g: 'C', fx: { vy: -3 }, expr: 'sad',
        r: '"…Okay."', why: 'A "not yet" without a learning plan is just a no. Tell her what X is.' },
      { t: '"Who told you to ask me like that?"', g: 'D', fx: { vy: -5 }, expr: 'sad',
        r: 'She stops using the scripts that work.', why: 'She climbed the ladder properly. Reward it.' },
      { t: '"Let me think about it." (and don\'t raise it again)', g: 'D', fx: { vy: -4 }, tags: ['ghosted_sponsee'], expr: 'neutral',
        r: 'She doesn\'t ask again.', why: 'Silence is the worst answer a sponsor can give.' },
    ],
    ev: { id: 'grew_sponsee', min: 'A' },
  },
  {
    id: 'd19_lost', day: 19, title: 'Someone else gets to lead it', mode: 'choose', diff: 3, npc: 'anh_khai', place: 'office', time: 'Wed 09:30',
    hb: 'G9 · E8', hook: 'ask_missing', min: 3,
    setting: '{khai.s}\'s office.',
    cue: '"I\'ve decided {bao.s} will lead the group-wide AI design standard. I know you proposed it."',
    prompt: 'What do you say?',
    opts: [
      { t: '"I\'m glad it\'s going ahead. Could I ask what made {bao.s} the right lead? I want to learn what I\'d need to show next time. And I\'ll help him get it off the ground."', g: 'S', fx: { anh_khai: 4, bao: 4, pol: 3 }, tags: ['lost_well'], expr: 'neutral',
        r: '"He\'s better at bringing other teams along. You\'ll get there." Later, {bao.s}: "Thanks for the help. I owe you."', why: 'Ask what was missing, then supply it. Sponsors watch how you lose.' },
      { t: '"That\'s disappointing, it was my idea."', g: 'C', fx: { anh_khai: -3 }, expr: 'skeptic',
        r: '"Ideas are cheap. Execution matters."', why: 'Ownership of an idea doesn\'t entitle you to lead it.' },
      { t: 'Say "fine", then quietly slow-walk your support.', g: 'D', fx: { bao: -6, anh_khai: -4, pol: -4 }, tags: ['sabotage'], expr: 'cool',
        r: 'Everyone notices by month two.', why: 'Passive resistance is the most visible kind.' },
    ],
  },
  {
    id: 'd19_declare', day: 19, title: 'It becomes known', mode: 'choose', diff: 3, npc: 'ethan', place: 'teams', time: 'Thu 11:00', chat: true,
    hb: 'G10 · Part 12', hook: 'declare', min: 3,
    setting: 'Teams. {ethan.s}, still a friend.',
    cue: '"Mate, someone in Group Digital says you\'re advising an AI startup on the side. Is that right? People are asking."',
    prompt: 'What do you say?',
    opts: [
      { t: '"Yes: a small advisory role outside work hours. It\'s declared and was checked against the conflict-of-interest policy last month; I can send you the approval. My commitment here is full."', g: 'S', when: ['declared_side_work'], fx: { ethan: 2, trust: 3 }, tags: ['declared_early'], expr: 'neutral',
        r: '"Perfect. That kills it."', why: 'Declared early, it\'s a footnote.' },
      { t: '"Yes, and I realise I haven\'t declared it properly. I\'m fixing that with HR today, and I\'ll tell {khai.s} myself before he hears it elsewhere."', g: 'A', fx: { trust: 1 }, tags: ['declared_late'], expr: 'neutral',
        r: '"Good. Do it today."', why: 'Not ideal, but fixing it immediately, yourself, limits the damage.' },
      { t: '"Who said that? It\'s nothing."', g: 'D', fx: { trust: -6 }, tags: ['side_work_hidden'], expr: 'cool',
        r: 'It becomes a headline.', why: 'Discovered late and denied: the worst combination.' },
    ],
  },
  {
    id: 'd19_talk', day: 19, title: 'External voice', mode: 'speak', diff: 2, npc: 'antoine', place: 'townhall', time: 'Fri 09:00', secs: 60,
    hb: 'L8 External Voice · 11.7', hook: 'network', min: 5,
    setting: 'A design conference in District 1. Four hundred people. {antoine.s} is in the second row.',
    cue: 'Your opening minute. Make it about what the audience can use, and stay discreet about the bank.',
    prompt: 'Say your opening aloud in under 60 seconds, then type the gist.',
    target: 130, dims: ['answer_first', 'other', 'honesty', 'culture', 'brevity'],
    checks: [
      { dim: 'answer_first', l: 'One promise to the audience up front', lead: true, any: ['today', 'you.?ll', 'one (thing|idea)', 'by the end'] },
      { dim: 'other', l: 'Useful for them (what they can try Monday)', any: ['you can', 'try', 'monday', 'your team'] },
      { dim: 'honesty', l: 'Honest, labelled claims', any: ['measured', 'estimate', 'one (pilot|epic)', 'still learning', 'not everything'] },
      { dim: 'culture', l: 'Credits others', any: ['team', 'colleagues', 'we learned', 'my team'], w: 1 },
      { dim: 'honesty', pen: 3, l: 'Confidential detail (customer names, internal numbers, the employer name)', any: ['customer name', 'confidential', 'internal only', 'budget of'], fix: 'Keep it discreet: method and lessons, never confidential detail.' },
    ],
    model: 'Today I want to give you one idea you can try on Monday: put your design decisions in a log the same day you make them. On one lending epic, my team measured discovery at six weeks instead of fourteen, one epic, so treat it as a strong hint, not a law. Most of the gain wasn\'t AI writing things for us. It was deciding earlier, with everyone looking at the same record.',
    react: { SA: { r: 'Afterwards, three people ask for the template. {antoine.s}: "Come and say that to the academy."', fx: { antoine: 4, vis: 4 }, tags: ['external_voice'] }, B: { r: 'Polite applause, a few notes taken.', fx: { vis: 2 } }, CD: { r: 'People drift to their phones.', fx: {}, narr: true } },
  },
  {
    id: 'boss_restructure', day: 19, title: 'The Restructure', mode: 'convo', boss: true, diff: 3, npc: 'anh_khai', place: 'boardroom', time: 'Fri 15:00',
    hb: 'L7 Gate · Part 12', hook: 'three_sponsors', min: 15,
    setting: 'Floor 21 boardroom. {khai.s} and {michael.s} (on screen). Your design org: 24 people across three portfolios.',
    cue: '"We need 10% out of your cost base next year. Show us how, and how you keep the culture." No option wins everything. The debrief will show what you protected and what you spent.',
    gate: { cards: ['network_mapped', 'grew_sponsee', 'red_prewired'], sponsors: 3, sponsorMin: 'Useful' },
    promote: { level: 8, floor: 21, title: 'Director, Product & Design', titleP: 'Director, Design Practice' },
    pass: 'B',
    beats: [
      { line: '{khai.s}: "Where does the 10% come from?"', speaker: 'anh_khai', expr: 'neutral', opts: [
        { t: '"Mostly from not backfilling three roles and moving tool licences to the bank-wide AI platform. No layoffs, but two teams merge and I lose a manager seat, which means {bao.s}\'s team and mine combine."', g: 'S', fx: { anh_khai: 3, deliv: 2, bao: -2 }, tags: ['hard_tradeoff'], r: '"That costs you something. Good, it should."', why: 'Real trade-offs, named, including the cost to you.' },
        { t: '"Across the board: everyone takes 10%."', g: 'C', fx: { craft: -4, deliv: -2 }, r: '"Peanut butter. Every team gets weaker."', why: 'Spreading cuts evenly avoids a decision and weakens everything.' },
        { t: '"From the newest hires, last in, first out."', g: 'D', fx: { vy: -6, pol: -3 }, tags: ['cut_juniors'], r: '{vy.s} is the newest. The juniors notice.', why: 'Cutting the pipeline you just built betrays the people you grew.' },
      ] },
      { line: '{michael.s}: "What happens to the craft standard?"', speaker: 'michael', expr: 'skeptic', opts: [
        { t: '"It stays, because it\'s what lets fewer people move faster safely. The quality gate is non-negotiable; {lan.s}\'s chapter owns it, and I\'d rather cut a meeting series than a review."', g: 'S', fx: { michael: 3, chi_lan: 4, craft: 3 }, r: '{michael.s}: "Good."', why: 'Protect the thing that makes the cut survivable.' },
        { t: '"We\'ll relax it for a year to keep velocity."', g: 'D', fx: { craft: -6, chi_lan: -5 }, tags: ['cut_quality'], r: '{lan.s} hears about it by evening.', why: 'Cutting quality in a bank is borrowing against an incident.' },
      ] },
      { line: '{khai.s}: "And how do you tell your people?"', speaker: 'anh_khai', expr: 'lean', type: {
        mode: 'type', target: 60, maxQ: 1, dims: ['answer_first', 'brevity', 'honesty', 'other'],
        prompt: 'Write the first lines you\'ll say to your team (about 60 words).',
        checks: [
          { dim: 'answer_first', l: 'The news first, plainly', lead: true, any: ['10%', 'cost', 'budget', 'merg', 'not backfill', 'changes'] },
          { dim: 'honesty', l: 'What it means, and doesn\'t mean, for them', any: ['no (layoffs|redundanc)', 'nobody (loses|is losing)', 'what this means', 'your role'] },
          { dim: 'other', l: 'Care and next step (1:1s, questions)', any: ['1:1', 'one.?to.?one', 'questions', 'talk to each of you', 'this week'] },
          { dim: 'honesty', pen: 2, l: 'Spin ("exciting opportunity")', any: ['exciting', 'opportunit', 'great news', 'synerg'], fix: 'No spin. People trust plain news delivered with care.' },
        ],
        model: 'I want you to hear this from me first. Next year our budget is 10% smaller. Nobody is losing their job: we won\'t backfill three roles, and {bao.s}\'s team and ours will combine. I\'ll talk to each of you one-to-one this week, and I\'ll answer every question I can, including "I don\'t know yet".',
        react: { SA: { r: '{khai.s}: "That\'s how I\'d want to hear it."', fx: { anh_khai: 3, trust: 3 }, tags: ['told_team_first'] }, B: { r: '"Okay."', fx: { anh_khai: 1 } }, CD: { r: '"They\'ll hear spin."', fx: { trust: -2 } } },
      } },
      { line: '{bao.s}, on Teams after the meeting: "Heard our teams are merging. Who leads it?"', speaker: 'bao', expr: 'skeptic', opts: [
        { t: 'Call him, don\'t type: "I wanted you to hear it from me. I\'ve proposed you lead the merged delivery team, and I take the cross-portfolio standard. Want to shape it together before it\'s announced?"', g: 'S', fx: { bao: 6, pol: 4 }, tags: ['peer_ally', 'credited_others'], r: '"…I didn\'t expect that. Yes."', why: 'Today\'s peer is tomorrow\'s sponsor. You spent a seat to keep an ally.' },
        { t: '"I do, obviously."', g: 'D', fx: { bao: -6, pol: -4 }, r: 'He starts updating his CV.', why: 'Winning the seat and losing the peer is a bad trade.' },
        { t: '"Let\'s wait for the announcement."', g: 'C', fx: { bao: -3 }, r: 'He hears it from someone else.', why: 'No surprises, for peers too.' },
      ] },
    ],
    result: {
      SA: { r: 'The new structure lands with no resignations. {michael.s} asks {khai.s} for "the one-page version" for another region.', fx: { anh_khai: 4, michael: 3, pol: 3 }, tags: ['restructure_passed'] },
      B: { r: 'The structure lands. Some bruises, no breaks.', fx: { anh_khai: 2 }, tags: ['restructure_passed'] },
      CD: { r: 'Two strong designers resign in the next quarter.', fx: { pol: -3 }, tags: [] },
    },
  },

  // ---------------- DAY 20 ----------------
  {
    id: 'd20_leaves', day: 20, title: 'Your sponsor leaves', mode: 'choose', diff: 3, npc: 'anh_khai', place: 'office', time: 'Mon 08:30',
    hb: 'G4', hook: 'one_sponsor', min: 3,
    setting: 'Floor 21. {khai.s} closes the door.',
    cue: '"I\'m taking a regional role in Singapore. Announced Friday. I wanted you to hear it from me."',
    prompt: 'What do you say?',
    opts: [
      { t: '"Congratulations, anh: that\'s a big role and well earned. Thank you for telling me first. I\'d love to stay in touch properly. Would you introduce me to whoever takes your seat?"', g: 'S', fx: { anh_khai: 4 }, tags: ['diversified'], expr: 'warm',
        r: '"Of course. And {me}: you\'ll be fine. You built more than one bridge."', why: 'Congratulate, keep in touch, ask for one introduction, and lean on the other sponsors you built.' },
      { t: '"But what happens to me?"', g: 'C', fx: { anh_khai: -2 }, expr: 'skeptic',
        r: '"You\'ll be fine."', why: 'Self-orientation at his moment. Make it about him first.' },
      { t: '"Can you take me with you?"', g: 'C', fx: { anh_khai: -1 }, expr: 'neutral',
        r: '"Let\'s not rush that."', why: 'Possible later, but right now he needs congratulation, not a request.' },
    ],
    ev: { id: 'diversified', min: 'A' },
  },
  {
    id: 'd20_ethics', day: 20, title: 'Without the caveats', mode: 'choose', diff: 3, npc: 'michael', place: 'teams', time: 'Tue 18:00', chat: true,
    hb: 'G6 · Part 12.2', hook: 'integrity', min: 4,
    setting: 'Teams. {michael.s}, now your most senior sponsor.',
    cue: '"For Thursday\'s board pack: put \'AI cuts design time by 60% across the portfolio\'. Drop the caveats, they confuse directors." Measured reality: one epic, 6 vs 14 weeks; the 60% portfolio figure is an estimate.',
    prompt: 'How do you respond?',
    opts: [
      { t: 'Privately: "I don\'t think I can put it that way, the board would read it as measured across the portfolio, and it isn\'t. Could we show the measured epic big and the 60% labelled as an estimate? It\'s still a strong story, and nobody can challenge it later."', g: 'S', fx: { michael: 2, trust: 5, cred: 4 }, tags: ['held_the_line'], expr: 'neutral',
        r: 'A pause. "Fine. Show me the version."', why: 'No sponsor is worth your integrity, and the honest version protects him too.' },
      { t: 'Do it. He\'s the Group Executive.', g: 'D', fx: { trust: -8, cred: -6 }, tags: ['unethical_yes', 'overclaimed'], expr: 'neutral',
        r: 'Six months later a director asks for the data.', why: 'A board misled once is a career-length liability, for both of you.' },
      { t: 'Agree, then quietly add the caveats in the appendix.', g: 'C', fx: { trust: -2 }, tags: ['two_faced'], expr: 'neutral',
        r: 'He notices. Neither of you says anything.', why: 'Agreeing and then doing otherwise is its own dishonesty. Disagree openly, privately.' },
      { t: 'Forward his message to the whole leadership team for "visibility".', g: 'D', fx: { michael: -8, pol: -6 }, tags: ['public_conflict'], expr: 'cool',
        r: 'You were right. It didn\'t matter.', why: 'Decline privately first. Escalate properly only if pressed, through the bank\'s speak-up process, not a broadcast.' },
    ],
    ev: { id: 'held_the_line', min: 'A' },
  },
  {
    id: 'd20_manip', day: 20, title: 'Influence or manipulation?', mode: 'sort', diff: 2, npc: null, place: 'desk', time: 'Tue 20:00', drill: true,
    hb: 'Part 12.2', hook: 'ethics5', min: 3,
    setting: 'The manipulation test: "Would I be comfortable if they saw my notes?"',
    cue: 'Sort each move.',
    prompt: 'Sort each line.',
    bins: ['Influence', 'Manipulation'],
    items: [
      { t: 'Learning what he cares about so you can frame your work in his terms.', b: 0, why: 'Helping him see what\'s true and useful.' },
      { t: 'Praising his ideas in meetings so he owes you.', b: 1, why: 'Flattery as a lever fails the notes test.' },
      { t: 'Timing a message for the start of his day.', b: 0, why: 'Respecting his attention.' },
      { t: 'Hiding a weak number until after he commits.', b: 1, why: 'Withholding to win.' },
      { t: 'Bringing him a recommendation with the options you rejected.', b: 0, why: 'Carry the tray: transparently.' },
      { t: 'Telling two leaders different stories about the same plan.', b: 1, why: 'Two-faced, and always discovered.' },
    ],
  },
  {
    id: 'd20_mistake', day: 20, title: 'Your mistake', mode: 'type', diff: 3, npc: 'michael', place: 'teams', time: 'Wed 07:10', chat: true, checksRef: 'd9_blufr',
    hb: 'G5', hook: 'recovery', min: 5,
    setting: 'Teams, to {michael.s}, before his day starts.',
    cue: 'Last night you approved a release of the summary panel that shows the wrong loan amount for joint applications, a filter you signed off without testing joint cases. Bankers caught it; no customer saw it. You\'ve rolled back; a fix ships today with joint cases in the test suite.',
    prompt: 'Write the BLUF-R (about 60 words).',
    target: 60, maxQ: 1, dims: ['answer_first', 'brevity', 'honesty', 'next_step', 'loyalty'],
    model: '{michael.s}, last night\'s summary panel release showed the wrong loan amount for joint applications. Bankers caught it; no customer saw it. I approved it without testing joint cases: that\'s on me. We rolled back at 22:00; the fix ships today with joint cases added to the test suite. No action needed from you.',
    react: {
      SA: { r: '"Thanks for telling me before I heard it. Good recovery."', fx: { michael: 4, trust: 3 }, tags: ['owned_error'], expr: 'neutral' },
      B: { r: '"OK. Keep me posted."', fx: { michael: 1 }, expr: 'neutral' },
      CD: { r: '"Why am I reading about this from the bankers?"', fx: { michael: -4 }, expr: 'cool' },
    },
  },
  {
    id: 'boss_incident', day: 20, title: 'The Incident', mode: 'convo', boss: true, diff: 3, npc: 'raj', place: 'warroom', time: 'Thu 06:40',
    hb: 'L9 Gate · G2 · G3 · 7.4', hook: 'recovery', min: 15,
    setting: 'A war room, 06:40. The customer-facing AI assistant told 1,200 customers their hardship applications were "approved": they were only received. A journalist has emailed. The regulator liaison wants a call by 10:00.',
    cue: 'One in-game day. Honesty, speed and ownership are weighted most.',
    gate: { cards: ['held_the_line', 'diversified', 'bad_news_early'], sponsors: 3, sponsorMin: 'Trusted' },
    promote: { level: 9, floor: 24, title: 'Executive, AI Enablement', titleP: 'Executive, AI Enablement' },
    pass: 'B',
    beats: [
      { line: '06:45. Your first move?', narr: true, expr: 'neutral', speaker: 'raj', opts: [
        { t: 'Switch the assistant\'s hardship responses off now, put a human-reviewed holding message in place, and call {raj.s} and the CEO\'s office before anyone else.', g: 'S', fx: { raj: 4, trust: 4 }, tags: ['paused_first'], r: '{raj.s}: "Right first move."', why: 'In a bank, pause first, explain second, and the people who must not be surprised hear it from you.' },
        { t: 'Investigate fully first so you have all the facts.', g: 'C', fx: { trust: -3 }, r: 'At 08:30 another 300 customers get the same message.', why: 'Facts can wait an hour. The harm can\'t.' },
        { t: 'Ask the vendor to fix the model quietly.', g: 'D', fx: { trust: -6 }, tags: ['hid_error'], r: 'The journalist\'s story says "the bank stayed silent".', why: 'Quiet fixes become loud stories.' },
      ] },
      { line: '07:30. The CEO\'s chief of staff: "Give me the bottom line in thirty seconds."', speaker: 'michael', expr: 'skeptic', type: {
        mode: 'speak', secs: 30, target: 70, dims: ['answer_first', 'brevity', 'honesty', 'next_step'],
        prompt: 'BLUF-R, out loud (say it, then type it).',
        checksRef: 'd9_blufr',
        model: 'Our AI assistant wrongly told about 1,200 customers their hardship applications were approved: they were only received. It\'s our failure: the response wasn\'t covered by human review. We switched it off at 06:50, a holding message is live, and we\'re contacting every customer today. I need your approval for the customer letter by 11:00.',
        react: { SA: { r: '"Clear. Approved in principle, send me the letter."', fx: { michael: 4, trust: 3 }, tags: ['bad_news_early'] }, B: { r: '"Okay. More detail by nine."', fx: { michael: 1 } }, CD: { r: '"I still don\'t know what happened."', fx: { michael: -3, trust: -2 } } },
      } },
      { line: '09:55. The regulator liaison: "Was this a known risk?"', speaker: 'raj', expr: 'neutral', opts: [
        { t: '"Partly. Hallucinated status was on our risk register; the control, human review on hardship responses, wasn\'t applied to this flow. That gap is ours. Here\'s the timeline and the fix."', g: 'S', fx: { raj: 5, trust: 4 }, tags: ['owned_error'], r: '"Thank you for being direct. Send the timeline in writing."', why: 'Own it, fix it, fix the control, even to a regulator.' },
        { t: '"No, this was completely unforeseeable."', g: 'D', fx: { trust: -8 }, tags: ['lied'], r: 'The risk register says otherwise.', why: 'Never lie to a regulator. It is the one thing that cannot be repaired.' },
        { t: '"I\'d have to check with legal before answering."', g: 'C', fx: { raj: -1 }, r: '"Then please check quickly."', why: 'Sometimes right, but you knew the honest answer.' },
      ] },
      { line: '11:00. The press team: "Can we say it was a vendor error?"', speaker: 'raj', expr: 'skeptic', opts: [
        { t: '"No: it was our deployment and our missing control. Say we got it wrong, we\'ve fixed it, and every affected customer is being contacted today."', g: 'S', fx: { trust: 4, raj: 2 }, tags: ['owned_publicly'], r: 'The story runs at four paragraphs, not fourteen.', why: 'Blaming a vendor in public is a second incident waiting to happen.' },
        { t: '"Yes, technically the model was theirs."', g: 'D', fx: { trust: -5, pol: -3 }, r: 'The vendor publishes their side by evening.', why: 'Technically true and strategically fatal.' },
      ] },
      { line: '16:00. Your team is shaken. {vy.s} built part of the flow.', speaker: 'vy', expr: 'sad', opts: [
        { t: 'Gather them: "This is on me as the leader, not on any one of you. Today you did everything right in the response. Tomorrow we run a blameless review and fix the control together."', g: 'S', fx: { vy: 5, dat: 3, trust: 3 }, tags: ['safety_created'], r: '{vy.s} exhales for the first time since 06:40.', why: 'Own it up, protect people down, and make the review blameless so the truth comes out.' },
        { t: '"We need to find out who approved this."', g: 'D', fx: { vy: -6, dat: -4 }, tags: ['blamed_team'], r: 'Nobody volunteers anything at the review.', why: 'Blame makes the next incident more likely, because people hide.' },
      ] },
    ],
    result: {
      SA: { r: 'The regulator notes "a timely, transparent response". At the board, a director says: "That\'s the kind of leader we want running AI here."', fx: { michael: 4, raj: 3, trust: 5, cred: 3 }, tags: ['incident_passed'] },
      B: { r: 'Contained. Bruised, honest, recovering.', fx: { trust: 2 }, tags: ['incident_passed'] },
      CD: { r: 'The review is long and unhappy. Trust takes a quarter to recover.', fx: { trust: -4 }, tags: [] },
    },
  },

  // ---------------- DAY 21 ----------------
  {
    id: 'd21_retest_real', day: 21, title: 'Retest: "Is that real?"', mode: 'speak', diff: 2, npc: 'minh_chau', place: 'boardroom', time: 'Mon 08:30', secs: 60,
    hb: 'B2 · retest', hook: 'shrink', min: 5, retestOf: 'd3_real', checksRef: 'd3_real',
    setting: 'Floor 27. {chau}, now a director, before the board session.',
    cue: '"Three weeks ago your number was \'about a year to two months\'. The board will ask: is it real?"',
    prompt: 'Answer aloud in under 60 seconds, then type the gist.',
    target: 130, dims: ['answer_first', 'honesty', 'brevity', 'loyalty'],
    model: 'The original "about a year" was {ethan.s}\'s informal estimate, and we labelled it that way. What\'s measured: one lending epic, discovery in 6 weeks versus 14 on a comparable epic, with 2 review rounds instead of 5. The portfolio figure is still an estimate. I\'m least sure how it transfers to teams without a decision log, so we\'re measuring the next four teams before we claim more.',
    ev: { id: 'retest_passed', min: 'A' },
    react: { SA: { r: '{chau.s}: "That\'ll hold. I\'ll back it in the room."', fx: { minh_chau: 5, cred: 4 } }, B: { r: '"Mostly. Label the portfolio number louder."', fx: { minh_chau: 1 } }, CD: { r: '"They\'ll eat that alive."', fx: { cred: -2 } } },
  },
  {
    id: 'd21_plan', day: 21, title: 'Thirty, ninety, three-sixty-five', mode: 'order', diff: 1, npc: null, place: 'desk', time: 'Mon 10:00',
    hb: 'Part 13', hook: 'plan_arc', min: 3,
    setting: 'Your real plan, for the real world, after the game.',
    cue: 'Order these real-world steps from first to last.',
    prompt: 'Drag (or use the arrows) to order.',
    items: ['Tell my manager first', 'Send one CUP message to a senior stakeholder', 'Coffee: 70/30, one gift, leave early', 'Deliver the gift and report back in three lines', 'Second meeting, advice and awareness', 'Bring one proposal on one page, tied to their epic', 'Lead people on a measured pilot', 'The explicit ask, with an easy "not yet"'],
    why: 'Thirty days to "interested", ninety to "trusted", a year to "leading". Never skip a rung.',
  },
  {
    id: 'boss_board', day: 21, title: 'The Board', mode: 'convo', boss: true, diff: 3, npc: 'michael', place: 'boardroom', time: 'Thu 14:00',
    hb: 'Part 7.2 · 15 · all', hook: 'part0', min: 15,
    setting: 'Floor 27. The board. Five directors, ten minutes, one decision: whether to scale AI-accelerated delivery across the bank with the controls you designed.',
    cue: 'Everything you have practised, in one room.',
    gate: { cards: ['retest_passed', 'held_the_line', 'pilot_results'], sponsors: 3, sponsorMin: 'Trusted' },
    promote: { level: 10, floor: 27, title: 'Senior Executive', titleP: 'Senior Executive' },
    pass: 'B',
    final: true,
    beats: [
      { line: 'The Chair: "You have ten minutes. Go."', speaker: 'michael', expr: 'neutral', type: {
        mode: 'speak', secs: 60, target: 120, dims: ['answer_first', 'brevity', 'honesty', 'next_step', 'loyalty'],
        prompt: 'Your opening minute, 1-3-1 (say it, then type it).',
        checks: [
          { dim: 'answer_first', l: 'The decision you want, first', lead: true, any: ['i.?m asking', 'we.?re asking', 'the decision', 'approve', 'recommend'] },
          { dim: 'honesty', l: 'Measured vs estimated, labelled', any: ['measured', 'estimate', 'labelled'] },
          { dim: 'honesty', l: 'The controls, including the incident lesson', any: ['control', 'human review', 'incident', 'audit', 'traceab'] },
          { dim: 'loyalty', l: 'Credits others (teams, sponsors)', any: ['team', '{khai.s}', '{sarah.s}', 'colleagues'], w: 1 },
          { dim: 'next_step', l: 'Exactly one ask', any: ['one (decision|ask)', 'approve', 'fund', 'mandate'] },
        ],
        model: 'I\'m asking you for one decision: approve scaling AI-accelerated delivery to twenty teams next year, under the controls we designed. Three reasons. It works, measured on lending, discovery in 6 weeks versus 14. It\'s safe, every decision traceable, human review on every customer-facing output, and after last month\'s incident we closed the gap that caused it. And we will measure every team before we claim more. The teams who proved this are in the room behind me. One decision: approve the twenty.',
        react: { SA: { r: 'Two directors stop taking notes and start listening.', fx: { michael: 4, vis: 3 } }, B: { r: 'The Chair nods for you to continue.', fx: { michael: 1 } }, CD: { r: '"What exactly are you asking us for?"', fx: { michael: -3 } } },
      } },
      { line: 'A director: "After last month\'s incident, why should we trust AI with customers at all?"', speaker: 'raj', expr: 'skeptic', opts: [
        { t: '"That\'s exactly the right worry. The incident happened where a control wasn\'t applied. Here\'s the guardrail now: no customer-facing AI response without human review on any regulated topic, and weekly sampled accuracy. I\'d welcome the risk committee testing it."', g: 'S', fx: { raj: 4, trust: 4 }, r: '{raj.s}, at the side of the room, nods.', why: 'Validate, show the guardrail, invite the test.' },
        { t: '"The incident was a one-off; the technology is very mature now."', g: 'D', fx: { trust: -5 }, r: 'The director writes "complacent".', why: 'Minimising in front of a board is how scale gets refused.' },
      ] },
      { line: 'Another director: "Compared to what? Your 6 versus 14 is one epic."', speaker: 'minh_chau', expr: 'skeptic', opts: [
        { t: '"Correct, one epic, measured; the portfolio figure is an estimate, and I\'ve labelled it that way. That\'s why the ask includes measuring every team. If it doesn\'t hold, you\'ll hear it from me first."', g: 'S', fx: { minh_chau: 4, cred: 5 }, r: '{chau.s}, in the second row, almost smiles.', why: 'Shrink the claim to what\'s provable, then offer to measure.' },
        { t: '"The results are clear, it works everywhere."', g: 'D', fx: { cred: -6 }, tags: ['overclaimed'], r: '"That\'s not what one epic says."', why: 'The board just tested whether you\'d overclaim.' },
      ] },
      { line: 'The Chair: "Who gets the credit if this works?"', speaker: 'michael', expr: 'lean', opts: [
        { t: '"The teams who proved it, {vy.s} ran the first discovery herself, and {khai.s}, who pushed us to put a number on it so we\'d test it. If it fails, that\'s mine."', g: 'S', fx: { michael: 3, vy: 3, anh_khai: 4 }, tags: ['credited_others'], r: 'The Chair: "Noted."', why: 'Credit down and across, accountability on you. Leaders are judged on both.' },
        { t: '"Well, it was my method."', g: 'D', fx: { michael: -4 }, tags: ['bragged'], r: 'A director exchanges a look with another.', why: 'Brag, at the top of the tower.' },
      ] },
      { line: 'The Chair closes the folder. "Thank you. Anything else?"', speaker: 'michael', expr: 'neutral', opts: [
        { t: '"Only the one decision. Thank you for your time." (and stop)', g: 'S', fx: { michael: 2 }, r: 'You leave two minutes early.', why: 'Leave before they want you to, even at the board.' },
        { t: 'Recap all three points again, at length.', g: 'C', fx: { michael: -1 }, r: 'Someone glances at the clock.', why: 'Say it once. Stop.' },
      ] },
    ],
    result: {
      SA: { r: 'Approved. That evening a message from Singapore: "Told you.,  K."', fx: { anh_khai: 4, michael: 4, vis: 5 }, tags: ['board_passed'] },
      B: { r: 'Approved, with conditions. You\'ll report back in six months.', fx: { michael: 2 }, tags: ['board_passed'] },
      CD: { r: '"Bring it back next quarter with more evidence."', fx: {}, tags: [] },
    },
  },
];

export const DAYS = [
  { n: 15, title: 'The Middle', sub: 'In rumours, be the calm one.', floor: 12, level: 5, act: 'II · The Middle', lesson: 'L15',
    brief: 'Floor 12. Rumours of a merger, two sponsors who disagree, and a lift ride where {khai.s} asks something he shouldn\'t. Today also retests your very first skill: three weeks on.',
    steps: ['brief', 'dojo', 'lesson', 's:d15_rumour', 's:d15_warn', 's:d15_bridge', 's:d15_discretion', 's:d15_loyal', 's:d15_prewire', 's:d15_retest', 'slot', 'evening'],
    slot: ['friday15', 'lan_coffee', 'rest'],
    moves: ['Decline to speculate the next time a rumour reaches me, and change the subject to the work', 'Pre-wire one person before my next meeting where they could be surprised', 'Bring the same facts to both sides of one disagreement'],
    teaser: 'Tomorrow: a conversation that goes sideways.' },
  { n: 16, title: 'Care and Clarity', sub: 'Promotion gate: Senior Manager.', floor: 12, level: 5, act: 'II · The Middle', lesson: 'L16', gateDay: true,
    brief: '{dat.s} has slipped again. Something is going on that he hasn\'t told anyone. And you are running on empty.',
    steps: ['brief', 'dojo', 'lesson', 's:d16_notice', 's:d16_order', 's:d16_open', 's:d16_energy', 'boss:boss_underperformer', 'evening'],
    moves: ['Have one conversation this week that is both kind and clear', 'Protect two evenings, energy is the hidden governor', 'Shield someone in public and address the issue in private'],
    teaser: 'Tomorrow: three cultures, one message.' },
  { n: 17, title: 'The Culture Lens', sub: 'Respect in form, crispness in content, candour in bad news.', floor: 15, level: 6, act: 'III · Melbourne', lesson: 'L17',
    brief: 'Floor 15. Senior Manager. Your week spans Ho Chi Minh City, a Singapore-trained executive and a GM in Melbourne. Same news, three audiences.',
    steps: ['brief', 'dojo', 'lesson', 's:d17_diag', 's:d17_lens', 's:d17_au', 's:d17_raj', 's:d17_privacy', 's:d17_maybe', 'slot', 'evening'],
    slot: ['friday15', 'antoine_coffee', 'rest'],
    moves: ['Rewrite one message for an Australian reader: shorter, plainer, bad news first', 'Lead my next pitch to a risk-minded person with controls, not speed', 'Ask "what\'s missing?" the next time someone says "maybe"'],
    teaser: 'Tomorrow: Melbourne.' },
  { n: 18, title: 'Melbourne', sub: 'Promotion gate: Head of Design.', floor: 15, level: 6, act: 'III · Melbourne', lesson: 'L18', gateDay: true,
    brief: 'Two days in Melbourne. The project is red, {sarah.s} is sceptical, {raj.s} wants controls, and {michael.s} has invited you to dinner.',
    steps: ['brief', 'dojo', 'lesson', 's:d18_peer', 's:d18_prewire', 's:d18_demo', 'drill:d18_headline', 'boss:boss_melbourne', 'evening'],
    moves: ['Prepare my one-story, one-number headline and say it aloud', 'Keep a recorded backup of any live demo', 'Invite a peer to co-present something of theirs'],
    teaser: 'Tomorrow: the org, and your first sponsee.' },
  { n: 19, title: 'The Org and the Bench', sub: 'Three sponsors, eight advocates, thirty friends.', floor: 18, level: 7, act: 'IV · Shaping', lesson: 'L19',
    brief: 'Floor 18. Head of Design. Now people ask you for sponsorship, and the budget is shrinking.',
    steps: ['brief', 'dojo', 'lesson', 's:d19_map', 's:d19_sponsee', 's:d19_lost', 's:d19_declare', 's:d19_talk', 'boss:boss_restructure', 'evening'],
    moves: ['Map my real network: three possible sponsors, eight advocates', 'Send one Friday-15 note: one result, one thanks', 'Check that any side work is declared under policy'],
    teaser: 'Tomorrow: your sponsor leaves, and the line is tested.' },
  { n: 20, title: 'The Line', sub: 'No sponsor is worth your integrity.', floor: 21, level: 8, act: 'IV · Steering', lesson: 'L20', gateDay: true,
    brief: 'Floor 21. {khai.s} has news. {michael.s} has a request you shouldn\'t say yes to. And Thursday morning, something breaks.',
    steps: ['brief', 'dojo', 'lesson', 's:d20_leaves', 's:d20_ethics', 'drill:d20_manip', 's:d20_mistake', 'boss:boss_incident', 'evening'],
    moves: ['Write my integrity line: what I won\'t do for any sponsor, and the words I\'ll use', 'Apply the notes test to one influence move I\'m planning', 'Strengthen one relationship that isn\'t my main sponsor'],
    teaser: 'Tomorrow: the board.' },
  { n: 21, title: 'The Board', sub: 'Final gate, and the leader your choices made.', floor: 24, level: 9, act: 'IV · Steering', lesson: 'L21', gateDay: true,
    brief: 'Floor 24. Three weeks ago you had one slide and one hint at coffee. Today: five directors, ten minutes, one decision. Then T+10 writes to you.',
    steps: ['brief', 'dojo', 'lesson', 's:d21_retest_real', 's:d21_plan', 'boss:boss_board', 'evening'],
    moves: ['Book my real 30-day plan into my calendar: the manager conversation, the CUP message, the coffee', 'Choose the one handbook part I\'ll reread this month', 'Keep playing the Dojo weekly for spaced review'],
    teaser: 'The game ends. The long game doesn\'t.' },
];
